/** Generic broker protocol. Public Computer Use semantics live outside Desktop/Relay. */
export {
  COMPUTER_USE_HOST_PROTOCOL_MAJOR,
  COMPUTER_USE_HOST_PROTOCOL_MINOR,
  COMPUTER_USE_HOST_CONTROL_MAX_BYTES,
  COMPUTER_USE_HOST_PNG_MAX_BYTES,
  ComputerUseHostProtocolError,
  ComputerUseHostResultGate,
  assertComputerUseHostAttachmentMatchesResult,
  canonicalizeComputerUseJson,
  parseComputerUseHostAttachmentMetadata,
  parseComputerUseHostAuthorityScope,
  parseComputerUseHostContract,
  parseComputerUseHostControlMessage,
  parseComputerUseHostGenerationFence,
  parseComputerUseHostRejectedResult,
  projectComputerUseHostRejectionSettlement,
  stringifyCanonicalComputerUseJson,
  type ComputerUseHostAttachmentMetadata,
  type ComputerUseHostAuthorityScope,
  type ComputerUseHostCancel,
  type ComputerUseAttachmentClass,
  type ComputerUseAuthorityClass,
  type ComputerUseDisclosureClass,
  type ComputerUseEffectClass,
  type ComputerUseHostContract,
  type ComputerUseHostControlMessage,
  type ComputerUseHostGenerationFence,
  type ComputerUseHostProtocolVersion,
  type ComputerUseHostRequest,
  type ComputerUseHostReady,
  type ComputerUseHostRejectedResult,
  type ComputerUseHostRejectionReason,
  type ComputerUseHostResult,
  type ComputerUseHostResultExpectation,
  type ComputerUseHostResultMessage,
  type ComputerUseReplayClass,
  type ComputerUseJson,
  type ComputerUseSettlement,
} from "./protocol.js";
