/**
 * D396 Wave 1 — real OfficeCLI create + batch + read round-trip for ALL
 * THREE formats: .docx paragraph, .xlsx cell, .pptx slide + shape.
 *
 * Exercises the production `generateOffice` helper against a vendored
 * officecli binary (not stubs). Gated on `officeCliAvailable()` so hosts
 * without a platform binary skip cleanly.
 *
 * Tier: integration only — not picked up by `scripts/run-unit.sh`.
 */
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";
import type { MemoryAccessEnvelope } from "@nautilo/trust";
import {
  buildGetArgvRun as buildGetArgv,
  generateOffice,
  makeOfficeCreateRun,
  officeCliAvailable,
  resolveOfficeCliOrNull,
  type OfficeBatchCommand,
  type OfficeCliRunResult,
  type OfficeCreateRunFn,
} from "@nautilo/config/officecli";
import {
  createOfficeCliTool,
  type CreateOfficeCliToolDeps,
} from "../../../agent/src/tools/office/officecli";

function zeroConfigOfficeCliEnv(): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...process.env, OFFICECLI_SKIP_UPDATE: "1", PATH: "" };
  delete env["OFFICECLI_PATH"];
  return env;
}

const OFFICECLI_PROBE = { env: zeroConfigOfficeCliEnv() };

interface GetEnvelopeResult {
  readonly text: string | null;
  readonly type: string | null;
  readonly childCount: number | null;
  readonly children: readonly GetEnvelopeChild[];
}

interface GetEnvelopeChild {
  readonly path: string;
  readonly type: string;
  readonly text?: string;
  readonly style?: string;
  readonly listStyle?: string;
  readonly numFmt?: string;
  readonly phType?: string;
  readonly isTitle?: boolean;
}

function asRecord(value: unknown): Record<string, unknown> | null {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

function readString(record: Record<string, unknown>, key: string): string | null {
  const value = record[key];
  return typeof value === "string" ? value : null;
}

function readNumber(record: Record<string, unknown>, key: string): number | null {
  const value = record[key];
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function readBool(record: Record<string, unknown>, key: string): boolean | null {
  const value = record[key];
  return typeof value === "boolean" ? value : null;
}

/**
 * Parse the OfficeCLI `get --json` envelope and pull the first result's
 * text/type/children. The binary returns:
 *   { success, data: { matches, results: [{ path, type, text, children }] } }
 */
function parseGetEnvelope(stdout: string): GetEnvelopeResult {
  const trimmed = stdout.trim();
  if (trimmed.length === 0) {
    throw new Error("officecli get returned empty stdout");
  }
  const parsed = JSON.parse(trimmed) as unknown;
  const root = asRecord(parsed);
  if (root === null) throw new Error("officecli get stdout was not a JSON object");
  const data = asRecord(root["data"]);
  if (data === null) throw new Error("officecli get envelope missing data");
  const results = data["results"];
  if (!Array.isArray(results) || results.length === 0) {
    return { text: null, type: null, childCount: null, children: [] };
  }
  const first = asRecord(results[0]);
  if (first === null) {
    return { text: null, type: null, childCount: null, children: [] };
  }
  const childrenRaw = Array.isArray(first["children"]) ? first["children"] : [];
  const children: GetEnvelopeChild[] = childrenRaw.map((raw) => {
    const rec = asRecord(raw) ?? {};
    const format = asRecord(rec["format"]) ?? {};
    return {
      path: readString(rec, "path") ?? "",
      type: readString(rec, "type") ?? "",
      ...(readString(rec, "text") !== null ? { text: readString(rec, "text")! } : {}),
      ...(readString(rec, "style") !== null ? { style: readString(rec, "style")! } : {}),
      ...(readString(format, "listStyle") !== null ? { listStyle: readString(format, "listStyle")! } : {}),
      ...(readString(format, "numFmt") !== null ? { numFmt: readString(format, "numFmt")! } : {}),
      ...(readString(format, "phType") !== null ? { phType: readString(format, "phType")! } : {}),
      ...(readBool(format, "isTitle") !== null ? { isTitle: readBool(format, "isTitle")! } : {}),
    };
  });
  return {
    text: readString(first, "text"),
    type: readString(first, "type"),
    childCount: readNumber(first, "childCount"),
    children,
  };
}

/**
 * Write the generated bytes back to a fresh temp file so we can run `get`
 * against the bytes the way a Wave-2 caller (artifact store, agent tool)
 * would. `generateOffice` cleans up its own scratch dir before returning, so
 * `generated.path` is gone by the time the test inspects the result.
 */
function stageBytesForReadback(
  bytes: Uint8Array,
  fileName: string,
  run: OfficeCreateRunFn,
): { readonly path: string; readonly cleanup: () => void } {
  const scratch = mkdtempSync(join(tmpdir(), "office-create-readback-"));
  const filePath = join(scratch, fileName);
  writeFileSync(filePath, bytes);
  // Warm the resident so the subsequent `get` is fast; not strictly required,
  // but mirrors the production read path. Errors here are non-fatal.
  void run(["open", filePath, "--json"]).catch(() => {});
  return {
    path: filePath,
    cleanup: () => {
      try {
        rmSync(scratch, { recursive: true, force: true });
      } catch {
        // Best-effort.
      }
    },
  };
}

async function readNode(
  run: OfficeCreateRunFn,
  file: string,
  path: string,
  depth = 2,
): Promise<GetEnvelopeResult> {
  const argv = buildGetArgv({ file, path, depth, json: true });
  const result: OfficeCliRunResult = await run(argv);
  if (result.exitCode !== 0) {
    throw new Error(
      `officecli get ${path} exited ${result.exitCode}: ${result.stderr}\n${result.stdout}`,
    );
  }
  return parseGetEnvelope(result.stdout);
}

describe("officecli create round-trip (D396 Wave 1)", () => {
  const hasOfficeCli = officeCliAvailable(OFFICECLI_PROBE);
  const runTest = hasOfficeCli ? test : test.skip;

  runTest(
    hasOfficeCli
      ? ".docx: zero-config bundled binary → create blank → batch add paragraph → close → read back text"
      : ".docx round-trip (skipped: officeCliAvailable() is false — no executable officecli binary for this platform)",
    async () => {
      const binaryPath = resolveOfficeCliOrNull(OFFICECLI_PROBE);
      expect(binaryPath, "resolveOfficeCliOrNull after officeCliAvailable()").not.toBeNull();
      expect(binaryPath, "zero-config resolver should use the vendored OfficeCLI tree").toContain(
        join("packages", "server", "vendor", "officecli"),
      );
      const run = makeOfficeCreateRun({ binaryPath: binaryPath! });

      const commands: OfficeBatchCommand[] = [
        { command: "add", parent: "/body", type: "paragraph", props: { text: "D396 docx paragraph" } },
      ];
      const generated = await generateOffice({
        fileName: "d396-create-docx.docx",
        commands,
        run,
        locale: "en-US",
      });

      expect(generated.type).toBe("docx");
      expect(generated.bytes.byteLength, "docx byte size").toBeGreaterThan(100);
      expect(generated.bytes.subarray(0, 2).toString("utf8"), "docx zip header").toBe("PK");

      const staged = stageBytesForReadback(generated.bytes, "d396-create-docx.docx", run);
      try {
        const node = await readNode(run, staged.path, "/body/p[1]", 1);
        expect(node.type, "first child type").toBe("paragraph");
        expect(node.text, "paragraph text").toBe("D396 docx paragraph");
      } finally {
        staged.cleanup();
      }
    },
    120_000,
  );

  runTest(
    hasOfficeCli
      ? ".docx: one create call with a markdown add command produces native non-empty Word content"
      : ".docx markdown round-trip (skipped: officeCliAvailable() is false — no executable officecli binary for this platform)",
    async () => {
      const binaryPath = resolveOfficeCliOrNull(OFFICECLI_PROBE);
      expect(binaryPath).not.toBeNull();
      const binaryRun = makeOfficeCreateRun({ binaryPath: binaryPath! });
      const invocations: string[][] = [];
      const run: OfficeCreateRunFn = async (argv) => {
        invocations.push([...argv]);
        return binaryRun(argv);
      };

      const ownerId = "00000000-0000-4000-8000-000000000101";
      const agentId = "00000000-0000-4000-8000-000000000102";
      const roomId = "00000000-0000-4000-8000-000000000103";
      const namespaceId = "00000000-0000-4000-8000-000000000104";
      const envelope: MemoryAccessEnvelope = {
        ownerId,
        actorId: ownerId,
        agentId,
        roomId,
        readableNamespaces: [namespaceId],
        mutableNamespaces: [namespaceId],
        writableNamespaces: [namespaceId],
        toolPolicy: {},
      };
      let postImage: Uint8Array | undefined;
      const tool = createOfficeCliTool(
        { ownerId, agentId, roomId, turnId: "d573-markdown-turn", memoryAccessEnvelope: envelope },
        {
          run,
          resolveWorkspaceArtifact: (async (params: Parameters<NonNullable<CreateOfficeCliToolDeps["resolveWorkspaceArtifact"]>>[0]) => ({
            ok: true,
            artifact: null,
            physicalPath: `/artifacts/${params.logicalPath}`,
            artifactId: "d573-markdown-artifact",
            storageUri: "file:///artifacts/d573-markdown-native.docx",
            logicalPath: params.logicalPath,
          })) as unknown as NonNullable<CreateOfficeCliToolDeps["resolveWorkspaceArtifact"]>,
          workspaceCommitExecution: async (request) => {
            postImage = request.postImage;
            return {
              ok: true,
              revisionId: "d573-markdown-revision",
              artifactInternalId: "d573-markdown-artifact",
              artifactId: "d573-markdown-artifact",
            };
          },
        },
      );

      const result = JSON.parse(String(await tool.invoke({
        command: "create",
        out: "d573-markdown-native.docx",
        commands: [{
          command: "add",
          parent: "/body",
          type: "markdown",
          props: {
            markdown: "# D573 Heading\n\nA native paragraph.\n\n- First item\n- Second item",
          },
        }],
      }))) as { applied?: boolean };
      expect(result.applied).toBe(true);
      expect(postImage).toBeDefined();

      expect(invocations.filter((argv) => argv[0] === "create")).toHaveLength(1);
      expect(invocations.filter((argv) => argv[0] === "batch")).toHaveLength(1);
      expect(invocations.filter((argv) => argv[0] === "close")).toHaveLength(1);

      const staged = stageBytesForReadback(postImage!, "d573-markdown-native.docx", run);
      try {
        const body = await readNode(run, staged.path, "/body", 4);
        const heading = body.children.find((child) => child.text === "D573 Heading");
        const paragraph = body.children.find((child) => child.text === "A native paragraph.");
        const bullets = body.children.filter((child) => child.text === "First item" || child.text === "Second item");
        expect(heading).toMatchObject({ type: "paragraph", style: "Heading1" });
        expect(paragraph).toMatchObject({ type: "paragraph" });
        expect(bullets).toHaveLength(2);
        for (const bullet of bullets) {
          expect(bullet).toMatchObject({ type: "paragraph", listStyle: "bullet", numFmt: "bullet" });
        }
      } finally {
        staged.cleanup();
      }
    },
    120_000,
  );

  runTest(
    hasOfficeCli
      ? ".xlsx: create blank → batch set cell → close → read back value"
      : ".xlsx round-trip (skipped: officeCliAvailable() is false — no executable officecli binary for this platform)",
    async () => {
      const binaryPath = resolveOfficeCliOrNull(OFFICECLI_PROBE);
      expect(binaryPath).not.toBeNull();
      const run = makeOfficeCreateRun({ binaryPath: binaryPath! });

      const commands: OfficeBatchCommand[] = [
        { command: "set", path: "/Sheet1/A1", props: { value: "D396 xlsx cell" } },
      ];
      const generated = await generateOffice({
        fileName: "d396-create-xlsx.xlsx",
        commands,
        run,
      });

      expect(generated.type).toBe("xlsx");
      expect(generated.bytes.byteLength, "xlsx byte size").toBeGreaterThan(100);
      expect(generated.bytes.subarray(0, 2).toString("utf8"), "xlsx zip header").toBe("PK");

      const staged = stageBytesForReadback(generated.bytes, "d396-create-xlsx.xlsx", run);
      try {
        const node = await readNode(run, staged.path, "/Sheet1/A1", 0);
        expect(node.type, "cell type").toBe("cell");
        expect(node.text, "cell value text").toBe("D396 xlsx cell");
      } finally {
        staged.cleanup();
      }
    },
    120_000,
  );

  runTest(
    hasOfficeCli
      ? ".pptx: create blank → batch add slide + shape → close → read back shape"
      : ".pptx round-trip (skipped: officeCliAvailable() is false — no executable officecli binary for this platform)",
    async () => {
      const binaryPath = resolveOfficeCliOrNull(OFFICECLI_PROBE);
      expect(binaryPath).not.toBeNull();
      const run = makeOfficeCreateRun({ binaryPath: binaryPath! });

      const commands: OfficeBatchCommand[] = [
        { command: "add", parent: "/", type: "slide", props: { title: "D396 Slide Title" } },
        {
          command: "add",
          parent: "/slide[1]",
          type: "shape",
          props: {
            text: "D396 pptx shape body",
            x: "1cm",
            y: "5cm",
            width: "20cm",
            height: "3cm",
          },
        },
      ];
      const generated = await generateOffice({
        fileName: "d396-create-pptx.pptx",
        commands,
        run,
      });

      expect(generated.type).toBe("pptx");
      expect(generated.bytes.byteLength, "pptx byte size").toBeGreaterThan(100);
      expect(generated.bytes.subarray(0, 2).toString("utf8"), "pptx zip header").toBe("PK");

      const staged = stageBytesForReadback(generated.bytes, "d396-create-pptx.pptx", run);
      try {
        const slide = await readNode(run, staged.path, "/slide[1]", 1);
        expect(slide.type, "slide type").toBe("slide");
        // The title shape is auto-emitted by `add slide --prop title=...` and
        // carries phType=title. Body shapes carry text we passed in.
        const titleChild = slide.children.find((c) => c.isTitle === true || c.phType === "title");
        expect(titleChild, "title child shape").toBeDefined();
        expect(titleChild!.text, "title text").toBe("D396 Slide Title");

        const bodyChild = slide.children.find((c) => c.text === "D396 pptx shape body");
        expect(bodyChild, "body shape with our text").toBeDefined();
      } finally {
        staged.cleanup();
      }
    },
    120_000,
  );
});
