import { describe, test, expect, beforeAll } from "bun:test";
import { chmodSync, existsSync, mkdtempSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawn } from "node:child_process";

const cliDist = join(import.meta.dirname, "..", "..", "dist", "index.js");

function statusBody(
  setupState: string,
  viewer?: { genieCustomized: boolean },
): Record<string, unknown> {
  return {
    instanceId: "it-test",
    serverUrl: "http://127.0.0.1:9",
    deploymentMode: "local-self-host",
    setupState,
    claimRequired: setupState === "fresh-unclaimed",
    ...(viewer
      ? {
          viewer: {
            canManageServerSettings: true,
            genieCustomized: viewer.genieCustomized,
            byokConfigured: true,
            pinEnrolled: false,
            handleAutoGenerated: false,
            passwordWasTemp: null,
          },
        }
      : {}),
    recommendedSetupSurface: { kind: "cli", url: null },
  };
}

describe("nautilo setup apply-genie-defaults bearer (§14.2 integration)", () => {
  beforeAll(() => {
    if (!existsSync(cliDist)) {
      throw new Error(`missing ${cliDist}; run bun run build in apps/cli first`);
    }
  });

  test("claimed-needs-auth + genie logs skip; no 401", async () => {
    const server = Bun.serve({
      port: 0,
      fetch() {
        return Response.json(statusBody("claimed-needs-auth"));
      },
    });
    try {
      const dir = mkdtempSync(join(tmpdir(), "nautilo-genie-"));
      const f = join(dir, "setup.toml");
      writeFileSync(
        f,
        [
          "schemaVersion = 1",
          "[admin]",
          'handle = "owner"',
          'displayName = "Owner"',
          'password = { value = "longenough1" }',
          'pin = { value = "654321" }',
          "[claim]",
          'inviteCode = { value = "tok" }',
          "[genie]",
          'mode = "randomize"',
          "seed = 42",
        ].join("\n"),
      );
      try {
        chmodSync(f, 0o600);
      } catch {
        /* win32 */
      }
      const base = `http://127.0.0.1:${server.port}`;
      const r = await new Promise<{ status: number; stderr: string }>((resolve, reject) => {
        const child = spawn(
          process.execPath,
          [cliDist, "setup", "--file", f, "--server", base],
          { stdio: ["ignore", "pipe", "pipe"], cwd: join(import.meta.dirname, "..", "..") },
        );
        const err: Buffer[] = [];
        child.stderr?.on("data", (d: Buffer) => err.push(d));
        child.on("error", reject);
        child.on("close", (code) => {
          resolve({
            status: code ?? 0,
            stderr: Buffer.concat(err).toString("utf8"),
          });
        });
      });
      expect(r.status).toBe(2);
      expect(r.stderr).toContain("genie defaults skipped");
      expect(r.stderr.toLowerCase()).not.toContain("401");
    } finally {
      server.stop();
    }
  });

  test("fresh-unclaimed + genie: PUT /api/profile with redeem bearer", async () => {
    let statusCalls = 0;
    let putCalls = 0;
    const observed = { putAuth: null as string | null };
    const server = Bun.serve({
      port: 0,
      fetch(req) {
        const u = new URL(req.url);
        if (u.pathname === "/api/setup/status") {
          statusCalls++;
          if (statusCalls === 1) {
            return Response.json(statusBody("fresh-unclaimed"));
          }
          if (statusCalls === 2) {
            return Response.json(statusBody("ready", { genieCustomized: false }));
          }
          return Response.json(statusBody("ready", { genieCustomized: true }));
        }
        if (u.pathname.includes("/api/invites/") && u.pathname.endsWith("/redeem")) {
          return Response.json({
            ok: true,
            logtoSession: { accessToken: "redeemed-bearer", expiresIn: 3600 },
          });
        }
        if (u.pathname === "/api/profile" && req.method === "PUT") {
          putCalls++;
          observed.putAuth = req.headers.get("Authorization");
          return Response.json({ ok: true });
        }
        return new Response("nope", { status: 404 });
      },
    });
    try {
      const dir = mkdtempSync(join(tmpdir(), "nautilo-genie-profile-"));
      const f = join(dir, "setup.toml");
      writeFileSync(
        f,
        [
          "schemaVersion = 1",
          "[admin]",
          'handle = "owner"',
          'displayName = "Owner"',
          'password = { value = "longenough1" }',
          'pin = { value = "654321" }',
          "[claim]",
          'inviteCode = { value = "inv_x" }',
          "[genie]",
          'mode = "explicit"',
          'name = "Smoke"',
          'voice = "openai:nova"',
          'defaultModel = "openai:gpt-4o-mini"',
          'personality = "Warm integration test personality line."',
          'avatar = { kind = "skip" }',
        ].join("\n"),
      );
      try {
        chmodSync(f, 0o600);
      } catch {
        /* win32 */
      }
      const base = `http://127.0.0.1:${server.port}`;
      const r = await new Promise<{ status: number; stderr: string }>((resolve, reject) => {
        const child = spawn(
          process.execPath,
          [cliDist, "setup", "--file", f, "--server", base],
          { stdio: ["ignore", "pipe", "pipe"], cwd: join(import.meta.dirname, "..", "..") },
        );
        const err: Buffer[] = [];
        child.stderr?.on("data", (d: Buffer) => err.push(d));
        child.on("error", reject);
        child.on("close", (code) => {
          resolve({
            status: code ?? 0,
            stderr: Buffer.concat(err).toString("utf8"),
          });
        });
      });
      expect(r.status).toBe(0);
      expect(observed.putAuth).toBe("Bearer redeemed-bearer");
      expect(putCalls).toBe(1);
    } finally {
      server.stop();
    }
  });

  test("no genie block — no PUT /api/profile", async () => {
    const paths: string[] = [];
    let statusN = 0;
    const server = Bun.serve({
      port: 0,
      fetch(req) {
        const u = new URL(req.url);
        paths.push(`${req.method} ${u.pathname}`);
        if (u.pathname === "/api/setup/status") {
          statusN++;
          if (statusN === 1) return Response.json(statusBody("fresh-unclaimed"));
          return Response.json(statusBody("ready", { genieCustomized: false }));
        }
        if (u.pathname.includes("/redeem")) {
          return Response.json({
            ok: true,
            logtoSession: { accessToken: "tok", expiresIn: 3600 },
          });
        }
        return new Response("nope", { status: 404 });
      },
    });
    try {
      const dir = mkdtempSync(join(tmpdir(), "nautilo-genie-"));
      const f = join(dir, "setup.toml");
      writeFileSync(
        f,
        [
          "schemaVersion = 1",
          "[admin]",
          'handle = "owner"',
          'displayName = "Owner"',
          'password = { value = "longenough1" }',
          'pin = { value = "654321" }',
          "[claim]",
          'inviteCode = { value = "inv_x" }',
        ].join("\n"),
      );
      try {
        chmodSync(f, 0o600);
      } catch {
        /* win32 */
      }
      const base = `http://127.0.0.1:${server.port}`;
      const r = await new Promise<{ status: number }>((resolve, reject) => {
        const child = spawn(
          process.execPath,
          [cliDist, "setup", "--file", f, "--server", base],
          { stdio: ["ignore", "pipe", "pipe"], cwd: join(import.meta.dirname, "..", "..") },
        );
        child.on("error", reject);
        child.on("close", (code) => resolve({ status: code ?? 0 }));
      });
      expect(r.status).toBe(0);
      expect(paths.some((p) => p.includes("PUT") && p.includes("/api/profile"))).toBe(false);
    } finally {
      server.stop();
    }
  });
});
