import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { KEY_REGISTRY } from "@nautilo/config-guard";
import {
  bootstrapDirForInstance,
  loadOperatorSecrets,
  markBootstrapUsed,
  writeBootstrapAdminPassword,
  writeBootstrapAdminPin,
  writeBootstrapClaimInvite,
} from "@nautilo/operator-secrets";
import {
  sweepLegacyProfileEnvBootstrapTokens,
  type ProfileEnvSweepEntry,
} from "./bootstrap-token-migration.ts";

/** Same compact ISO shape as `m091IsoCompactStamp` in config-guard / bootstrap-token-migration. */
function m091IsoCompactStamp(date: Date): string {
  return date
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d{3}Z$/, "Z");
}

/** Must stay in sync with `packages/operator-secrets/src/shared.ts`. */
const BOOTSTRAP_ADMIN_RE = /^NAUTILO_BOOTSTRAP_ADMIN_PASSWORD_[A-Z0-9_]+$/;
const BOOTSTRAP_PIN_RE = /^NAUTILO_BOOTSTRAP_PIN_[A-Z0-9_]+$/;
const CLAIM_INVITE_RE = /^NAUTILO_CLAIM_INVITE_[A-Z0-9_]+$/;

const registryEnvVars = new Set(KEY_REGISTRY.map((k) => k.envVar));

function operatorConfigDir(home: string): string {
  return join(home, ".config", "nautilo");
}

function operatorSecretsPath(home: string): string {
  return join(operatorConfigDir(home), "secrets.env");
}

function resolveDeployTomlExamplePath(home: string): string {
  return join(operatorConfigDir(home), "deploy.toml.example");
}

function isBootstrapKey(key: string): boolean {
  return (
    BOOTSTRAP_ADMIN_RE.test(key) || BOOTSTRAP_PIN_RE.test(key) || CLAIM_INVITE_RE.test(key)
  );
}

function isProviderKey(key: string): boolean {
  return registryEnvVars.has(key);
}

function extractBootstrapSuffix(key: string): string | null {
  if (BOOTSTRAP_ADMIN_RE.test(key)) {
    return key.slice("NAUTILO_BOOTSTRAP_ADMIN_PASSWORD_".length);
  }
  if (BOOTSTRAP_PIN_RE.test(key)) {
    return key.slice("NAUTILO_BOOTSTRAP_PIN_".length);
  }
  if (CLAIM_INVITE_RE.test(key)) {
    return key.slice("NAUTILO_CLAIM_INVITE_".length);
  }
  return null;
}

/** Reverse of `instanceIdToSecretSuffix` in operator-secrets (lossy for `_` vs `-`). */
function suffixToInstanceId(suffix: string): string {
  return suffix.toLowerCase().replace(/_/g, "-");
}

/**
 * Resolve the on-disk root for a decoded instance id. MUST use the
 * lowercased/normalized id, NOT the raw uppercase env-suffix — instance
 * directories are created lowercase (`.nautilo-beta`) and Linux is
 * case-sensitive (CI failure mode).
 */
function instanceRootForInstanceId(home: string, instanceId: string): string {
  const dash = instanceId === "" ? "" : `-${instanceId}`;
  return join(home, `.nautilo${dash}`);
}

export function listNautiloInstanceRoots(home: string): string[] {
  const out: string[] = [];
  let names: string[];
  try {
    names = readdirSync(home);
  } catch {
    return [];
  }
  for (const name of names) {
    if (name !== ".nautilo" && !name.startsWith(".nautilo-")) continue;
    const p = join(home, name);
    try {
      if (statSync(p).isDirectory()) out.push(p);
    } catch {
      /* skip */
    }
  }
  return out.sort();
}

function instanceIdFromInstanceRoot(root: string, home: string): string {
  const rel = root.slice(home.length).replace(/^\/+/, "");
  if (rel === ".nautilo") return "";
  if (rel.startsWith(".nautilo-")) return rel.slice(".nautilo-".length);
  return rel;
}

function suffixKeyForInstanceId(instanceId: string): string {
  return instanceId.trim().replace(/-/g, "_").toUpperCase();
}

function buildDeployTomlExample(providerEnvVars: string[]): string {
  const sorted = [...new Set(providerEnvVars)].sort();
  const providerBlocks = sorted
    .map(
      (envVar) => `[[providers]]
key = "${envVar}"
value = { fromEnv = "${envVar}" }
`,
    )
    .join("\n\n");
  return `# ~/.config/nautilo/deploy.toml — operator deploy input
#
# This file replaces ~/.config/nautilo/secrets.env's role for new deployments.
# Provider API keys live here; per-instance bootstrap rows now live in
# ~/.nautilo-<instance>/.bootstrap/ (one file per kind, mode 0600).
#
# Generated by \`nautilo doctor migrate-config\` from your existing
# ~/.config/nautilo/secrets.env. Review and rename to deploy.toml when ready.

schemaVersion = 1

[admin]
# Fill before first deploy. handle is the operator account login name.
handle = "owner_handle"
displayName = "Primary Owner"
# This is your permanent owner password. Keep it in protected operator custody.
password = { fromEnv = "NAUTILO_ADMIN_PASSWORD" }
pin = { fromEnv = "NAUTILO_ADMIN_PIN" }

# Provider keys imported from your existing operator secrets file.
# Each is referenced via { fromEnv = "..." } so deploy.toml can be checked
# into a private secret store without inlining values.
${providerBlocks}
[genie]
mode = "skip"
`;
}

const DEPRECATED_SECRETS_HEADER = `# ~/.config/nautilo/secrets.env — DEPRECATED
#
# Per-instance bootstrap rows have moved to each instance's ~/.nautilo-*/.bootstrap/.
# This file now only carries operator-wide provider API keys, kept for
# back-compat with \`nautilo setup --secrets-file\`. See:
#   ~/.config/nautilo/deploy.toml.example
#
# This file will be removed in a future minor release. Migrate via:
#   nautilo doctor migrate-config
`;

function extractEnvLineKey(line: string): string | null {
  const trimmed = line.trim();
  if (trimmed.length === 0 || trimmed.startsWith("#")) return null;
  let rest = trimmed;
  if (/^export\s+/i.test(rest)) {
    rest = rest.replace(/^export\s+/i, "").trimStart();
  }
  const eq = rest.indexOf("=");
  if (eq === -1) return null;
  return rest.slice(0, eq).trim();
}

function buildProviderOnlySecretsBody(originalBody: string): string {
  const keptLines: string[] = [];
  for (const rawLine of originalBody.split(/\r?\n/)) {
    const key = extractEnvLineKey(rawLine);
    if (!key) {
      if (rawLine.trim() !== "") keptLines.push(rawLine);
      continue;
    }
    if (isBootstrapKey(key)) continue;
    keptLines.push(rawLine);
  }
  const bodyRest = keptLines.join("\n").trimEnd();
  const sep = bodyRest.length > 0 ? "\n\n" : "\n";
  return `${DEPRECATED_SECRETS_HEADER}${sep}${bodyRest}${bodyRest.length > 0 ? "\n" : ""}`;
}

export interface DoctorMigrateConfigOptions {
  home?: string;
  now?: Date;
  dryRun?: boolean;
  /** Override for tests; defaults wired at CLI call site. */
  checkInstanceClaimedFn?: (instanceRoot: string, instanceId: string) => Promise<boolean>;
}

export type BootstrapFileKind = "admin-password" | "admin-pin" | "claim-invite";

export interface PerInstanceMaterializationOutcome {
  instanceId: string;
  instanceRoot: string;
  filesWritten: BootstrapFileKind[];
  markedUsed: boolean;
  claimCheckError?: string;
}

export interface DoctorMigrateConfigResult {
  status:
    | "no-op-already-migrated"
    | "no-op-no-secrets-file"
    | "migrated"
    | "dry-run";
  operatorFilePath: string;
  deployTomlExamplePath: string;
  operatorFileBackupPath: string | null;
  providerKeysExtracted: string[];
  perInstance: PerInstanceMaterializationOutcome[];
  /** Result of sweeping `~/.nautilo/profiles/*.env` for legacy bootstrap tokens (Phase 6 retirement). */
  profileEnvSweep: ProfileEnvSweepEntry[];
  warnings: string[];
  discoveredInstanceRoots: string[];
  dryRunWrites?: { path: string; bytes: number }[];
}

function recordDryRun(
  dryRunWrites: { path: string; bytes: number }[] | undefined,
  path: string,
  bytes: number,
  dryRun: boolean,
): void {
  if (dryRun && dryRunWrites) {
    dryRunWrites.push({ path, bytes });
  }
}

export async function runDoctorMigrateConfig(
  opts?: DoctorMigrateConfigOptions,
): Promise<DoctorMigrateConfigResult> {
  const home = opts?.home?.trim() || process.env["HOME"] || "";
  if (!home) {
    throw new Error("HOME is not set (pass opts.home for tests)");
  }
  const now = opts?.now ?? new Date();
  const dryRun = Boolean(opts?.dryRun);
  const dryRunWrites: { path: string; bytes: number }[] | undefined = dryRun ? [] : undefined;

  const operatorFilePath = operatorSecretsPath(home);
  const deployTomlExamplePath = resolveDeployTomlExamplePath(home);
  const warnings: string[] = [];
  const discoveredInstanceRoots = listNautiloInstanceRoots(home);

  const suffixToRoots = new Map<string, string[]>();
  for (const root of discoveredInstanceRoots) {
    const id = instanceIdFromInstanceRoot(root, home);
    const sk = suffixKeyForInstanceId(id);
    const arr = suffixToRoots.get(sk) ?? [];
    arr.push(root);
    suffixToRoots.set(sk, arr);
  }
  for (const [sk, roots] of suffixToRoots) {
    if (roots.length > 1) {
      warnings.push(
        `Multiple instance directories share secret suffix ${sk} (${roots.join(", ")}); ` +
          `bootstrap env suffix decode is lossy (e.g. test-1 vs test_1 both map to ${sk}).`,
      );
    }
  }

  // Phase 6 retirement: sweep legacy `~/.nautilo/profiles/*.env` files for any
  // residual bootstrap-token lines and migrate to ~/.nautilo/bootstrap-tokens/.
  // Independent of the secrets.env work — runs even when secrets.env is missing
  // or already migrated. Skipped in dry-run mode (the sweep helper itself mutates
  // disk and has no dry-run option; we surface the planned work as a warning instead).
  let profileEnvSweep: ProfileEnvSweepEntry[];
  if (dryRun) {
    profileEnvSweep = [];
    const profilesDir = join(home, ".nautilo", "profiles");
    if (existsSync(profilesDir)) {
      warnings.push(
        `dry-run: would sweep ${profilesDir} for legacy <name>.env bootstrap-token lines and migrate any matches to ~/.nautilo/bootstrap-tokens/`,
      );
    }
  } else {
    profileEnvSweep = sweepLegacyProfileEnvBootstrapTokens({ home, now });
  }

  if (!existsSync(operatorFilePath)) {
    return {
      status: "no-op-no-secrets-file",
      operatorFilePath,
      deployTomlExamplePath,
      operatorFileBackupPath: null,
      providerKeysExtracted: [],
      perInstance: [],
      profileEnvSweep,
      warnings,
      discoveredInstanceRoots,
      ...(dryRunWrites ? { dryRunWrites } : {}),
    };
  }

  const opStat = statSync(operatorFilePath);
  if (existsSync(deployTomlExamplePath)) {
    const depStat = statSync(deployTomlExamplePath);
    if (depStat.mtimeMs >= opStat.mtimeMs) {
      return {
        status: "no-op-already-migrated",
        operatorFilePath,
        deployTomlExamplePath,
        operatorFileBackupPath: null,
        providerKeysExtracted: [],
        perInstance: [],
        profileEnvSweep,
        warnings,
        discoveredInstanceRoots,
        ...(dryRunWrites ? { dryRunWrites } : {}),
      };
    }
  }

  const parsed = await loadOperatorSecrets(operatorFilePath);
  const rawBody = readFileSync(operatorFilePath, "utf8");

  const providerKeysExtracted: string[] = [];
  const bootstrapBySuffix = new Map<
    string,
    { adminPassword?: string; adminPin?: string; claimInvite?: string }
  >();

  for (const key of Object.keys(parsed)) {
    if (isBootstrapKey(key)) {
      const suf = extractBootstrapSuffix(key);
      if (!suf) continue;
      const row = bootstrapBySuffix.get(suf) ?? {};
      const v = parsed[key] ?? "";
      if (BOOTSTRAP_ADMIN_RE.test(key)) row.adminPassword = v;
      if (BOOTSTRAP_PIN_RE.test(key)) row.adminPin = v;
      if (CLAIM_INVITE_RE.test(key)) row.claimInvite = v;
      bootstrapBySuffix.set(suf, row);
      continue;
    }
    if (isProviderKey(key)) {
      providerKeysExtracted.push(key);
      continue;
    }
    warnings.push(
      `operator file contains unrecognized key ${key}; left in place in rewritten secrets.env`,
    );
  }

  providerKeysExtracted.sort();

  const deployBody = buildDeployTomlExample(providerKeysExtracted);
  const newSecretsBody = buildProviderOnlySecretsBody(rawBody);

  const backupBase = `secrets.env.pre-m091.${m091IsoCompactStamp(now)}.bak`;
  const operatorFileBackupPath = join(operatorConfigDir(home), backupBase);

  const perInstanceMap = new Map<string, PerInstanceMaterializationOutcome>();

  for (const [suffix, payload] of bootstrapBySuffix) {
    const instanceId = suffixToInstanceId(suffix);
    const instanceRoot = instanceRootForInstanceId(home, instanceId);
    const filesWritten: BootstrapFileKind[] = [];
    if (!existsSync(instanceRoot)) {
      warnings.push(
        `operator file contains row for instance '${instanceId}' but no ${instanceRoot} directory found; skipping materialization`,
      );
      continue;
    }
    const bootstrapDir = bootstrapDirForInstance(instanceId, { home });
    if (payload.adminPassword !== undefined) {
      filesWritten.push("admin-password");
      if (dryRun) {
        recordDryRun(dryRunWrites, join(bootstrapDir, "admin-password"), payload.adminPassword.length, dryRun);
      } else {
        writeBootstrapAdminPassword(bootstrapDir, payload.adminPassword);
      }
    }
    if (payload.adminPin !== undefined) {
      filesWritten.push("admin-pin");
      if (dryRun) {
        recordDryRun(dryRunWrites, join(bootstrapDir, "admin-pin"), payload.adminPin.length, dryRun);
      } else {
        writeBootstrapAdminPin(bootstrapDir, payload.adminPin);
      }
    }
    if (payload.claimInvite !== undefined) {
      filesWritten.push("claim-invite");
      if (dryRun) {
        recordDryRun(dryRunWrites, join(bootstrapDir, "claim-invite"), payload.claimInvite.length, dryRun);
      } else {
        writeBootstrapClaimInvite(bootstrapDir, payload.claimInvite);
      }
    }
    perInstanceMap.set(instanceId, {
      instanceId,
      instanceRoot,
      filesWritten,
      markedUsed: false,
    });
  }

  for (const outcome of perInstanceMap.values()) {
    if (outcome.filesWritten.length === 0) continue;
    const fn = opts?.checkInstanceClaimedFn;
    if (!fn) continue;
    try {
      const claimed = await fn(outcome.instanceRoot, outcome.instanceId);
      if (claimed && !dryRun) {
        markBootstrapUsed(bootstrapDirForInstance(outcome.instanceId, { home }), { now });
        outcome.markedUsed = true;
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      outcome.claimCheckError = msg;
      warnings.push(
        `claim-status check failed for instance '${outcome.instanceId}' (${outcome.instanceRoot}): ${msg}`,
      );
    }
  }

  if (!dryRun) {
    mkdirSync(operatorConfigDir(home), { recursive: true, mode: 0o700 });
    copyFileSync(operatorFilePath, operatorFileBackupPath);
    chmodSync(operatorFileBackupPath, 0o600);
    writeFileSync(operatorFilePath, newSecretsBody, { encoding: "utf8", mode: 0o600 });
    chmodSync(operatorFilePath, 0o600);
    writeFileSync(deployTomlExamplePath, deployBody, { encoding: "utf8", mode: 0o644 });
    chmodSync(deployTomlExamplePath, 0o644);
  } else {
    recordDryRun(dryRunWrites, operatorFileBackupPath, rawBody.length, dryRun);
    recordDryRun(dryRunWrites, operatorFilePath, Buffer.byteLength(newSecretsBody, "utf8"), dryRun);
    recordDryRun(dryRunWrites, deployTomlExamplePath, Buffer.byteLength(deployBody, "utf8"), dryRun);
  }

  return {
    status: dryRun ? "dry-run" : "migrated",
    operatorFilePath,
    deployTomlExamplePath,
    operatorFileBackupPath: dryRun ? null : operatorFileBackupPath,
    providerKeysExtracted,
    perInstance: [...perInstanceMap.values()].sort((a, b) => a.instanceId.localeCompare(b.instanceId)),
    profileEnvSweep,
    warnings,
    discoveredInstanceRoots,
    ...(dryRunWrites ? { dryRunWrites } : {}),
  };
}
