import type { ResolvedInstance } from "@nautilo/config";
import { composeProjectName } from "./composeProjectName.ts";
import type { DbPasswords } from "./ensureDbPasswords.ts";
import {
  resolveLogtoAdminContainerEndpoint,
  resolveLogtoAdminPublicUrl,
  resolveLogtoPublicUrl,
  resolveServerBaseUrl,
} from "./instance-urls.ts";
import { httpsMode } from "./https-mode.ts";
import { DEPENDENCY_PINS } from "../../dependency-pins.ts";
import type { ComposeDriverProfile } from "./types.ts";
import { assertSourceBuildSha } from "./source-build-identity.ts";

/**
 * Pure mapper from `(profile, resolvedInstance)` to the env-file
 * `Record<string,string>` consumed by the deploy/full-stack compose
 * template. Keys mirror `templates/.env.local-smoke.example` 1:1 so
 * the template substitutions stay byte-identical between the M114
 * smoke and M092's CLI-driven deploy.
 *
 * Passwords are generated by `ensureDbPasswords()` on first `nautilo deploy`
 * (M116) and persisted to `~/.nautilo${suffix}/instance.env` via
 * config-guard. Subsequent deploys read from there. The manual smoke path
 * (`scripts/m114-docker-smoke.sh` + `.env.local-smoke.example`) keeps
 * well-known defaults for developer convenience on `127.0.0.1`.
 */
/** host[:port] of a URL (no scheme), for coolwsd `server_name`. Empty on parse failure. */
function publicHostFromUrl(url: string): string {
  try {
    return new URL(url).host;
  } catch {
    return "";
  }
}

export function buildComposeEnv(
  profile: ComposeDriverProfile,
  inst: ResolvedInstance,
  passwords: DbPasswords,
  opts?: { acmeEmail?: string; caddyfilePath?: string; sourceBuildSha?: string },
): Record<string, string> {
  const tag = profile.tag ?? "local-dev";
  const publicServerUrl = resolveServerBaseUrl(profile, inst);
  // M201 — coolwsd must emit URLs the BROWSER can reach, not the internal
  // `collabora:9980` compose-DNS host. `server_name` is the host[:port] the
  // browser uses (from the public base URL, no scheme); `ssl.termination` is
  // true ONLY when TLS is terminated at the edge (Caddy / letsencrypt) so
  // coolwsd emits wss/https — plain-http local/LAN deploys need ws/http.
  const publicHost = publicHostFromUrl(publicServerUrl);
  const coolwsdSslTermination = httpsMode(profile) === "letsencrypt" ? "true" : "false";

  const base: Record<string, string> = {
    COMPOSE_PROJECT_NAME: composeProjectName(profile),
    NAUTILO_SERVER_TAG: tag,
    ...(opts?.sourceBuildSha !== undefined
      ? { NAUTILO_SOURCE_SHA: assertSourceBuildSha(opts.sourceBuildSha) }
      : {}),
    NAUTILO_HOSTING_MODE: "local",
    // Emitted on the always-present --env-file so the base template's
    // `NAUTILO_INSTANCE_ID: ${NAUTILO_INSTANCE_ID:-}` resolves on every
    // compose invocation — deploy AND restore/rollback. Without this the id
    // lived only in the server overlay, so a rollback (which omitted that
    // overlay) silently demoted a named instance to the default one.
    NAUTILO_INSTANCE_ID: inst.instanceId,
    NAUTILO_PASSWORD_RECOVERY_DRIVER:
      profile.password_recovery ?? "oss_relay",
    NAUTILO_DEPLOY_APP_DB_PORT: String(inst.db.postgresHostPort),
    NAUTILO_DEPLOY_DB_PORT: String(inst.logto.dbPort),
    NAUTILO_DEPLOY_LOGTO_PORT: String(inst.logto.corePort),
    NAUTILO_DEPLOY_LOGTO_ADMIN_PORT: String(inst.logto.adminPort),
    NAUTILO_DEPLOY_SERVER_PORT: String(inst.server.port),
    NAUTILO_PUBLIC_BASE_URL: publicServerUrl,
    // M201 — office (coolwsd) server_name + ssl.termination inputs.
    NAUTILO_PUBLIC_HOST: publicHost,
    NAUTILO_COOLWSD_SSL_TERMINATION: coolwsdSslTermination,
    // M201 — runtime office feature flag for the server container, driven by
    // the per-profile `office` boolean. false (default) => no office tools /
    // routes / UI; the office+collabora compose profile is also not brought up.
    NAUTILO_OFFICE_ENABLED: profile.office === true ? "true" : "false",
    APP_DB_PASSWORD: passwords.appDbPassword,
    POSTGRES_USER: "postgres",
    POSTGRES_PASSWORD: passwords.postgresPassword,
    NAUTILO_DB_PASSWORD: passwords.nautilo,
    LOGTO_DB_PASSWORD: passwords.logto,
    NAUTILO_AGENT_DB_PASSWORD: passwords.nautiloAgent,
    NAUTILO_CRYPTO_DB_PASSWORD: passwords.nautiloCrypto,
    LOGTO_IMAGE_TAG: DEPENDENCY_PINS.logtoImageTag,
    POSTGRES_IMAGE: DEPENDENCY_PINS.postgres,
    PGVECTOR_IMAGE: DEPENDENCY_PINS.pgvectorPg17,
    LOGTO_IMAGE: DEPENDENCY_PINS.logto,
    LOGTO_ENDPOINT: resolveLogtoPublicUrl(profile, inst),
    // Public URL (browser / docs). Not wired into the Logto container —
    // see LOGTO_CONTAINER_ADMIN_ENDPOINT.
    LOGTO_ADMIN_ENDPOINT: resolveLogtoAdminPublicUrl(profile, inst),
    LOGTO_CONTAINER_ADMIN_ENDPOINT: resolveLogtoAdminContainerEndpoint(inst),
    // M117 — Logto must honor X-Forwarded-Proto from Caddy when LE is
    // active; otherwise the OIDC discovery doc + token/authorize URLs
    // are rendered as http:// (Caddy → Logto bridge is plain HTTP),
    // and the browser blocks the workbench's token-exchange POST as
    // mixed content. With TRUST_PROXY_HEADER=1, Logto uses the
    // forwarded scheme to construct public URLs as https://.
    LOGTO_TRUST_PROXY: httpsMode(profile) === "letsencrypt" ? "1" : "0",
    // M092 — the deploy stack always binds on `0.0.0.0` inside the
    // container (necessary for the host port-forward) but the host
    // port IS the trust boundary, so the LAN-host TLS branch would
    // self-sign a cert that has nowhere to surface to CLI/Electron.
    // Force plain HTTP; M117 adds Caddy as the TLS terminator for
    // public Droplets (https=letsencrypt) — Caddy runs in front of
    // the container and reverse-proxies plain HTTP on the bridge.
    NAUTILO_DISABLE_TLS: "1",
  };

  if (httpsMode(profile) === "letsencrypt") {
    return {
      ...base,
      NAUTILO_DOMAIN: profile.domain ?? "",
      ACME_EMAIL: opts?.acmeEmail ?? "",
      NAUTILO_DEPLOY_CADDYFILE_PATH: opts?.caddyfilePath ?? "",
    };
  }

  return base;
}
