export const CANONICAL_RUNTIME_IMAGE = "ghcr.io/agentsea/nautilo-runtime-v2";
const LEGACY_RUNTIME_IMAGE = "ghcr.io/agentsea/nautilo-runtime";

const ADMITTED_RUNTIME_IMAGES = new Set([CANONICAL_RUNTIME_IMAGE, LEGACY_RUNTIME_IMAGE]);
const SHA256_DIGEST_RE = /^sha256:[a-f0-9]{64}$/;

/**
 * Validates the only registry authority accepted by new Compose deploys.
 *
 * Tags are useful for discovery, but never identify a deployable artifact:
 * callers must provide the approved public runtime manifest digest.
 */
export function buildRegistryImageRef(imageRef: string): string {
  const trimmed = imageRef.trim();
  const separator = trimmed.indexOf("@");
  const repository = separator === -1 ? "" : trimmed.slice(0, separator);
  const digest = separator === -1 ? "" : trimmed.slice(separator + 1);
  if (!ADMITTED_RUNTIME_IMAGES.has(repository) || !SHA256_DIGEST_RE.test(digest)) {
    throw new Error(
      `Runtime image selection requires ${CANONICAL_RUNTIME_IMAGE}@sha256:<64-hex-digest> (or the legacy Nautilo runtime namespace during recovery migration).`,
    );
  }
  return trimmed;
}

/**
 * Renders a recovery overlay for an already-captured image reference.
 *
 * This deliberately accepts historical registry and local-source references:
 * backup/rollback must still be able to restore images recorded before the
 * public runtime cutover. New canonical deployment input goes through
 * `buildRegistryImageRef` instead.
 */
export function buildPinnedImageOverlay(imageRef: string): string {
  const trimmed = imageRef.trim();
  if (trimmed.length === 0) {
    throw new Error("Pinned image overlay requires a non-empty image ref.");
  }
  return [
    "# Generated by @nautilo/compose-driver — do not edit by hand.",
    "# Pins nautilo-server to the image captured in a backup bundle.",
    "services:",
    "  nautilo-server:",
    `    image: ${trimmed}`,
    "    build: !reset null",
    "",
  ].join("\n");
}

/**
 * Pure mapper: returns the compose overlay YAML that points
 * nautilo-server at the published registry image.
 *
 * The base template still carries the source-build shape for developer
 * mode. Registry deploy clears that inherited `build:` stanza with
 * Compose's `!reset` merge tag, then invokes compose with `pull` +
 * `up --no-build` so the droplet acts as a runtime, not a build machine.
 */
export function buildRegistryOverlay(imageRef: string): string {
  return buildPinnedImageOverlay(buildRegistryImageRef(imageRef)).replace(
    "Pins nautilo-server to the image captured in a backup bundle.",
    "Uses the immutable public Nautilo runtime image for registry-mode deploys.",
  );
}
