/**
 * Pure mapper: returns the compose overlay YAML adding the Caddy
 * service + named volumes, and suppressing ONLY nautilo-server's
 * published port so Caddy can own 80/443.
 *
 * IMPORTANT: a plain `ports: []` does NOT clear the inherited list —
 * Compose *merges* (concatenates) `ports` across `-f` files, so the
 * base template's `${NAUTILO_DEPLOY_SERVER_PORT}:3001` mapping would
 * survive and collide with Caddy when that port resolves to 443. The
 * `!reset []` tag forces a true override (same mechanism the pinned-
 * image restore overlay uses with `build: !reset null`).
 *
 * Why nautilo-server ONLY (NOT logto): Logto's user-facing OIDC port
 * keeps its existing host reachability, including same-network mobile
 * access to local deployments. The deploy's Logto bootstrap also
 * reaches the ADMIN port via an SSH tunnel to the droplet's host port
 * (`localhost:<adminPort>` → remote `127.0.0.1:<adminPort>`). The base
 * template publishes that admin port on host loopback only. An earlier
 * revision `!reset []`-ed logto and broke the bootstrap token mint (the
 * tunnel had nothing to connect to). Leave logto's `ports` block
 * untouched so both deliberate base-template publications survive.
 *
 * Layered onto base compose YAML via `docker compose -f <base>
 * -f <volumes-overlay> -f <this>` when https=letsencrypt.
 *
 * Takes no args today; M119 will grow this to accept profile for
 * port overrides.
 */
export function buildCaddyOverlay(): string {
  return [
    "# Generated by @nautilo/compose-driver (M117) — do not edit by hand.",
    "# Adds Caddy in front of nautilo-server + logto for https=letsencrypt.",
    "services:",
    "  caddy:",
    "    image: caddy:2-alpine",
    "    profiles: [\"app\", \"full\"]",
    "    depends_on:",
    "      nautilo-server:",
    "        condition: service_started",
    "      logto:",
    "        condition: service_started",
    "    ports:",
    "      - \"80:80\"",
    "      - \"443:443\"",
    "      - \"443:443/udp\"",
    "    volumes:",
    "      - ${NAUTILO_DEPLOY_CADDYFILE_PATH}:/etc/caddy/Caddyfile:ro",
    "      - caddy_data:/data",
    "      - caddy_config:/config",
    "    environment:",
    "      NAUTILO_DOMAIN: ${NAUTILO_DOMAIN}",
    "      NAUTILO_DEPLOY_LOGTO_PORT: ${NAUTILO_DEPLOY_LOGTO_PORT}",
    "      ACME_EMAIL: ${ACME_EMAIL}",
    "    restart: unless-stopped",
    "    networks:",
    "      - deploy-net",
    "",
    "  nautilo-server:",
    "    ports: !reset []",
    "",
    "volumes:",
    "  caddy_data:",
    "  caddy_config:",
    "",
  ].join("\n");
}
