import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const cliRoot = join(__dirname, "..");
const cliPkg = JSON.parse(readFileSync(join(cliRoot, "package.json"), "utf8")) as {
  version: string;
};
const apiPkg = JSON.parse(
  readFileSync(join(cliRoot, "../../packages/api-client/package.json"), "utf8"),
) as { version: string };

const contents = `// Generated by scripts/generate-version.ts — do not edit by hand.
export const VERSION = ${JSON.stringify(cliPkg.version)};
export const API_VERSION = ${JSON.stringify(apiPkg.version)};
`;

writeFileSync(join(cliRoot, "src/version.ts"), contents);
