/**
 * D510 Task 1.1 — pure characterization floor for the current wizard port.
 *
 * Electron cancellation, the final Reveal write, and Workbench completion
 * notification belong to Electron main-process/packaged coverage. They are
 * mapped in README.md and intentionally not simulated by this reducer test.
 */
import { describe, expect, test } from "bun:test";
import {
  nextReachableForTests,
  wizardReducerForTests,
  type WizardState,
} from "../src/hooks/useWizardState";
import { screenForOnboardingStartAt, type ProfileSnapshot } from "../src/types";

const FLAGS = { avatarGenAvail: true, motherEasterEgg: false } as const;

const EXISTING_PROFILE: ProfileSnapshot = {
  name: "Aster",
  language: "en",
  workLifeMode: "both",
  privacySpectrum: 73,
  personalityPrompt: "calm and precise",
  motherAnswer: null,
  defaultVoice: { voiceId: "voice-1", voiceName: "Atlas" },
  avatar: { kind: "preset", id: "avatar-01" },
  avatarUrl: "/api/onboarding/images/avatars/avatar-01.webp",
  soulFile: "existing soul",
};

function blankState(): WizardState {
  return wizardReducerForTests(
    {
      screen: 0,
      viewer: {
        genieCustomized: false,
        pinEnrolled: false,
        handleAutoGenerated: false,
        displayNameSet: false,
        recoveryCodesAcknowledged: false,
      },
      hydratedSnapshot: null,
      flags: { avatarGenAvail: false, motherEasterEgg: false },
      language: "en",
      privacySlider: 50,
      workLifeChoice: null,
      personalityPrompt: "",
      motherAnswer: "",
      compilingPhase: "idle",
      compilingGeneration: 0,
      soulFile: null,
      avatarSource: null,
      avatarChoice: null,
      avatarRef: null,
      avatarTarget: null,
      name: "",
      voiceSelection: null,
      voiceSkipped: false,
      voiceCapability: "unknown",
      errors: {},
    },
    { type: "RESET" },
  );
}

describe("D510 — current wizard boundary", () => {
  test("maps only the supported Desktop re-trigger targets", () => {
    expect(screenForOnboardingStartAt("personality")).toBe(5);
    expect(screenForOnboardingStartAt("avatar")).toBe(8);
    expect(screenForOnboardingStartAt(null)).toBeNull();
    expect(screenForOnboardingStartAt("voice")).toBeNull();
    expect(screenForOnboardingStartAt({ screen: 5 })).toBeNull();
  });

  test("hydrates a first-run session without a snapshot and keeps soul compilation reachable", () => {
    const hydrated = wizardReducerForTests(blankState(), {
      type: "HYDRATE",
      profile: null,
      flags: FLAGS,
    });

    expect(hydrated.hydratedSnapshot).toBeNull();
    expect(hydrated.viewer.genieCustomized).toBe(false);
    expect(hydrated.flags).toEqual(FLAGS);
    expect(nextReachableForTests(hydrated, 6)).toBe(6);
  });

  test("hydrates an existing profile as a re-trigger and skips unchanged soul compilation", () => {
    const hydrated = wizardReducerForTests(blankState(), {
      type: "HYDRATE",
      profile: EXISTING_PROFILE,
      flags: FLAGS,
    });

    expect(hydrated.hydratedSnapshot).not.toBeNull();
    expect(hydrated.viewer.genieCustomized).toBe(true);
    expect(hydrated.name).toBe("Aster");
    expect(hydrated.soulFile).toBe("existing soul");
    expect(hydrated.voiceSelection).toMatchObject({ voiceId: "voice-1" });
    expect(nextReachableForTests(hydrated, 7)).toBe(8);
  });

  test("makes a material re-trigger edit require a fresh soul before Avatar", () => {
    const hydrated = wizardReducerForTests(blankState(), {
      type: "HYDRATE",
      profile: EXISTING_PROFILE,
      flags: FLAGS,
    });
    const changed = wizardReducerForTests(hydrated, {
      type: "SET_PERSONALITY",
      value: "warm but still precise",
    });

    expect(changed.soulFile).toBeNull();
    expect(nextReachableForTests(changed, 6)).toBe(6);
  });

  test("records SKIP_VOICE as explicit UI skip while retaining no deletion intent", () => {
    const selected = wizardReducerForTests(blankState(), {
      type: "SET_VOICE",
      selection: {
        slug: "atlas",
        profileVoiceName: "Atlas",
        voiceId: "voice-1",
        soulLabel: "Atlas",
      },
    });
    const skipped = wizardReducerForTests(selected, { type: "SKIP_VOICE" });

    expect(skipped.voiceSelection).toBeNull();
    expect(skipped.voiceSkipped).toBe(true);
  });
});
