import { z } from "zod";

/** Runtime `AvatarRef` from @nautilo/types — distinct from setup-template `GenieAvatar`. */
export const avatarRefSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("preset"), id: z.string() }),
  z.object({ kind: z.literal("uploaded"), blobId: z.string() }),
  z.object({ kind: z.literal("generated"), blobId: z.string() }),
]);

const setupStateSchema = z.enum([
  "fresh-unclaimed",
  "claimed-needs-auth",
  "server-needs-keys",
  "ready",
]);

const recommendedSetupSurfaceKindSchema = z.enum([
  "electron-onboarding",
  "workbench-admin",
  "cli",
  "ask-admin",
]);

const instanceDeploymentModeSchema = z.enum([
  "local-self-host",
  "lan-self-host",
  "cloud-managed",
  "dev-multi-instance",
]);

/** D280 — server identity block (setup status + profile write responses). */
const serverProfileSchema = z.object({
  name: z.string(),
  description: z.string().nullable().optional(),
  // Present on POST /api/server/profile responses; omitted from redacted setup
  // status payloads — tolerate absence (D280 R7).
  descriptionVisibility: z.enum(["public", "members"]).optional(),
  icon: avatarRefSchema,
  reviewedAt: z.string().nullable().optional(),
});

export const serverProfileUpdateResponseSchema = z.object({
  serverProfile: serverProfileSchema,
});

/**
 * `GET /api/setup/status` — without a session omits `viewer`, `providers`,
 * and `claimInvitePathHint`, but still returns `recommendedSetupSurface`.
 * With `sessionUserId` the payload adds `viewer`, `providers`, `claimInvitePathHint`,
 * and a role-aware `recommendedSetupSurface`.
 */
export const setupStatusResponseSchema = z.object({
  instanceId: z.string(),
  serverUrl: z.string(),
  deploymentMode: instanceDeploymentModeSchema,
  // Optional for resilience: the server always sends it post-D280, but a
  // CLI/client may hit an older server that doesn't — tolerate its absence
  // (same pattern as `viewer`/`providers`).
  serverProfile: serverProfileSchema.optional(),
  setupState: setupStateSchema,
  claimRequired: z.boolean(),
  deployConfigConsumedAt: z.string().nullable().optional(),
  viewer: z
    .object({
      // D219 — replaces `serverRole`. True when the viewer holds
      // `manage_server_settings` (provider-key / model config). Gates the
      // keys / reload-env / claim-hint surfaces.
      canManageServerSettings: z.boolean(),
      // Optional for rolling compatibility. False suppresses every Genie
      // onboarding entrance for a capability-restricted Human (M259).
      canInvokeAgents: z.boolean().optional(),
      genieCustomized: z.boolean(),
      byokConfigured: z.boolean(),
      pinEnrolled: z.boolean(),
      handleAutoGenerated: z.boolean(),
      passwordWasTemp: z.boolean().nullable(),
    })
    .optional(),
  providers: z
    .object({
      hasLlm: z.boolean(),
      // Optional so new clients continue to accept an authenticated response
      // from a server released before D508's secondary-provider projection.
      hasVoice: z.boolean().optional(),
      hasSearch: z.boolean().optional(),
      hasConversion: z.boolean().optional(),
      managedByCloud: z.boolean(),
    })
    .optional(),
  recommendedSetupSurface: z
    .object({
      kind: recommendedSetupSurfaceKindSchema,
      url: z.string().nullable(),
    })
    .optional(),
  claimInvitePathHint: z.string().nullable().optional(),
});

export type SetupStatusResponse = z.infer<typeof setupStatusResponseSchema>;
