/**
 * Built-in model policy only. This module intentionally knows nothing about
 * credentials, the active signed catalog, routing consent, or persisted
 * operator choices. `@nautilo/agent` resolves these ordered candidates through
 * the canonical availability machinery.
 */
export const MODEL_ROLE_CANDIDATES = {
  chat: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:openai/gpt-5.6-terra",
    "venice:openai-gpt-56-terra",
    "openai:gpt-5.6-terra",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:openai/gpt-5.5",
    "venice:openai-gpt-55-pro",
    "openai:gpt-5.5-2026-04-23",
    "openrouter:z-ai/glm-5.1",
    "openrouter:moonshotai/kimi-k2.6",
  ],
  conductor: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:openai/gpt-5.6-luna",
    "venice:openai-gpt-56-luna",
    "openai:gpt-5.6-luna",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:z-ai/glm-5.1",
    "venice:zai-org-glm-5-1",
  ],
  stenographer: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:openai/gpt-5.6-luna",
    "venice:openai-gpt-56-luna",
    "openai:gpt-5.6-luna",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:z-ai/glm-5.1",
    "venice:zai-org-glm-5-1",
  ],
  sessionSearch: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:openai/gpt-5.6-luna",
    "venice:openai-gpt-56-luna",
    "openai:gpt-5.6-luna",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:z-ai/glm-5.1",
    "venice:zai-org-glm-5-1",
    "openrouter:minimax/minimax-m2.7",
    "venice:minimax-m27",
    "fireworks:accounts/fireworks/models/minimax-m3",
  ],
  memoryFlush: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:openai/gpt-5.6-luna",
    "venice:openai-gpt-56-luna",
    "openai:gpt-5.6-luna",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:z-ai/glm-5.1",
    "venice:zai-org-glm-5-1",
    "fireworks:accounts/fireworks/models/glm-5p3",
  ],
  memoryReview: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:openai/gpt-5.6-luna",
    "venice:openai-gpt-56-luna",
    "openai:gpt-5.6-luna",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:z-ai/glm-5.1",
    "venice:zai-org-glm-5-1",
    "fireworks:accounts/fireworks/models/glm-5p3",
  ],
  webSearchSynthesis: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:minimax/minimax-m2.7",
    "venice:minimax-m27",
    "fireworks:accounts/fireworks/models/minimax-m3",
  ],
  systemTasks: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:openai/gpt-5.6-luna",
    "venice:openai-gpt-56-luna",
    "openai:gpt-5.6-luna",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:z-ai/glm-5.1",
    "venice:zai-org-glm-5-1",
  ],
  deepResearchSupervisor: [
    "openrouter:moonshotai/kimi-k3",
    "venice:kimi-k3",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:openai/gpt-5.5",
    "venice:openai-gpt-55-pro",
    "openai:gpt-5.5-2026-04-23",
    "openrouter:moonshotai/kimi-k2.6",
    "fireworks:accounts/fireworks/models/kimi-k3",
  ],
  deepResearchResearcher: [
    "openrouter:moonshotai/kimi-k3",
    "venice:kimi-k3",
    "openrouter:moonshotai/kimi-k2.6",
    "fireworks:accounts/fireworks/models/kimi-k3",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:openai/gpt-5.5",
    "venice:openai-gpt-55-pro",
    "openai:gpt-5.5-2026-04-23",
  ],
  deepResearchSynthesis: [
    "openrouter:moonshotai/kimi-k3",
    "venice:kimi-k3",
    "openrouter:moonshotai/kimi-k2.6",
    "fireworks:accounts/fireworks/models/kimi-k3",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:openai/gpt-5.5",
    "venice:openai-gpt-55-pro",
    "openai:gpt-5.5-2026-04-23",
  ],
  deepResearchFinalReport: [
    "openrouter:moonshotai/kimi-k3",
    "venice:kimi-k3",
    "openrouter:openai/gpt-5.5",
    "venice:openai-gpt-55-pro",
    "openai:gpt-5.5-2026-04-23",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
    "openrouter:moonshotai/kimi-k2.6",
    "fireworks:accounts/fireworks/models/kimi-k3",
  ],
  embeddings: [
    "venice:text-embedding-qwen3-8b",
    "openrouter:qwen/qwen3-embedding-8b",
    "venice:text-embedding-3-small",
    "openrouter:openai/text-embedding-3-small",
    "openai:text-embedding-3-small",
  ],
  visionFallback: [
    "openrouter:minimax/minimax-m3",
    "venice:minimax-m3-preview",
    "openrouter:anthropic/claude-sonnet-4.6",
    "venice:claude-sonnet-4-6",
    "anthropic:claude-sonnet-4-6",
    "openrouter:google/gemini-3.1-pro-preview",
    "venice:gemini-3-1-pro-preview",
    "google:gemini-3.1-pro-preview",
  ],
  imageGeneration: [
    "openai:gpt-image-2.5-sunburst",
    "openai:gpt-image-2.5-flare",
    "venice:gpt-image-2",
    "openrouter:openai/gpt-5.4-image-2",
    "openrouter:openai/gpt-image-2",
    "openai:gpt-image-2",
    "google:gemini-2.5-flash-image",
  ],
} as const;

export type ModelRole = keyof typeof MODEL_ROLE_CANDIDATES;

export function candidatesForModelRole(role: ModelRole): readonly string[] {
  return MODEL_ROLE_CANDIDATES[role];
}
