// Modified by Nautilo: retain attached endpoints after PPTX shape ID assignment.
import type { Endpoint } from '../../model/connector.js';
import type { Element } from '../../model/element.js';
import { flattenElements } from '../../model/group.js';
import { getConnectionSites } from '../../view/canvas/connection-sites/index.js';
import { escapeXmlAttr } from './xml.js';

/**
 * Resolve attachments after the existing serializer assigns slide-local IDs.
 * This operates only on XML generated by our serializers, never imported XML.
 * Groups share the slide ID space, so forward and nested references work too.
 */
export function attachConnectors(
  body: string,
  elements: Element[],
  spidMap: ReadonlyMap<string, number>,
): string {
  const byName = new Map(flattenElements(elements).map(el => [escapeXmlAttr(el.id), el]));

  function endpointXml(tag: 'stCxn' | 'endCxn', endpoint: Endpoint): string {
    if (endpoint.kind === 'free') return '';
    const name = escapeXmlAttr(endpoint.elementId);
    const id = spidMap.get(endpoint.elementId);
    const target = byName.get(name);
    if (id === undefined || !target) {
      throw new Error('Cannot export a connector whose attached target is missing from the slide export.');
    }
    if (!Number.isSafeInteger(endpoint.siteIndex) || endpoint.siteIndex < 0
      || endpoint.siteIndex >= getConnectionSites(target).length) {
      throw new Error('Cannot export a connector with an invalid attachment site.');
    }
    // Inverse of import/pptx/shape.ts: rect-family sites are N,E,S,W in
    // the model and T,L,B,R in OOXML; ellipse sites already use OOXML order.
    const rectSites: readonly number[] = [0, 3, 2, 1];
    const index = target.type === 'shape' && target.data.kind === 'ellipse'
      ? endpoint.siteIndex
      : rectSites[endpoint.siteIndex] ?? endpoint.siteIndex;
    return `<a:${tag} id="${id}" idx="${index}"/>`;
  }

  return body.replace(/<p:cxnSp>[\s\S]*?<\/p:cxnSp>/g, xml => {
    const name = /<p:cNvPr id="\d+" name="([^"]*)"/.exec(xml)?.[1];
    const connector = name === undefined ? undefined : byName.get(name);
    if (!connector || connector.type !== 'connector') {
      throw new Error('Cannot resolve a serialized connector to its source element.');
    }
    const connections = endpointXml('stCxn', connector.start) + endpointXml('endCxn', connector.end);
    return connections
      ? xml.replace('<p:cNvCxnSpPr/>', `<p:cNvCxnSpPr>${connections}</p:cNvCxnSpPr>`)
      : xml;
  });
}
