import { join } from "node:path";
import type { FastifyInstance, FastifyRequest } from "fastify";
import {
  readDeployConfigConsumedAt,
  resolveInstance,
  resolveNautiloRootDir,
  slugifyToHandle,
} from "@nautilo/config";
import {
  check,
  reloadEnvAndStripRemovedRegistryKeys,
  resolveDotenvPath,
} from "@nautilo/config-guard";
import { getProfile } from "@nautilo/agent";
import {
  db,
  eq,
  getAccountSecurityRowByUserId,
  getServerProfile,
  deriveDefaultServerName,
  hasClaimedOwner,
  hasUnredeemedClaimInvite,
  type ResolvedServerProfile,
  users,
} from "@nautilo/db";
import type { AvatarRef } from "@nautilo/types";
import { getUserCapabilities, PinChallengeProvider } from "@nautilo/trust";
import { getServerDirectDb } from "../lib/server-direct-db";
import { resolvePublicServerUrl, resolvePublicWorkbenchUrl } from "../lib/public-urls";
import { requestAllowsLoopbackTrust } from "../lib/request-trust";
import { error as logError } from "@nautilo/logger";

export const SETUP_STATES = [
  "fresh-unclaimed",
  "claimed-needs-auth",
  "server-needs-keys",
  "ready",
] as const;

export type SetupState = (typeof SETUP_STATES)[number];

export type RecommendedSetupSurfaceKind =
  | "electron-onboarding"
  | "workbench-admin"
  | "cli"
  | "ask-admin";

function managedByCloudFromInstance(): boolean {
  return resolveInstance().deploymentMode === "cloud-managed";
}

function shouldExposeClaimInvitePathHint(request: FastifyRequest): boolean {
  return requestAllowsLoopbackTrust(request);
}

type ViewerUserRow = {
  name: string;
  handle: string | null;
};

async function resolveViewerUserRow(userId: string): Promise<ViewerUserRow | null> {
  const directDb = getServerDirectDb();
  const [row] = await directDb
    .select({ name: users.name, handle: users.handle })
    .from(users)
    .where(eq(users.id, userId))
    .limit(1);
  if (!row) return null;
  return { name: row.name, handle: row.handle };
}

/**
 * D219 — replaces the `serverRole === "admin"` gate. `manage_server_settings`
 * is the capability that maps to provider-key / model config
 * (permission-model.md §5); it drives the `server-needs-keys` recommended
 * surface, the claim-invite path hint, and the `reload-env` admin gate.
 */
function buildPublicServerProfile(
  profile: ResolvedServerProfile,
  sessionUserId: string | null | undefined,
): {
  name: string;
  description?: string | null;
  descriptionVisibility?: "public" | "members";
  icon: AvatarRef;
  reviewedAt?: string | null;
} {
  const out: {
    name: string;
    description?: string | null;
    descriptionVisibility?: "public" | "members";
    icon: AvatarRef;
    reviewedAt?: string | null;
  } = {
    name: profile.name,
    icon: profile.icon,
  };
  if (profile.descriptionVisibility === "public" || sessionUserId) {
    out.description = profile.description;
  }
  // D220 Server section — echo the visibility flag to authed viewers so the
  // admin edit form reflects the persisted value instead of defaulting to
  // "public". Omitted for anonymous callers to keep the redacted payload lean.
  if (sessionUserId) {
    out.descriptionVisibility = profile.descriptionVisibility;
    out.reviewedAt = profile.reviewedAt?.toISOString() ?? null;
  }
  return out;
}

let resolveViewerCapabilities: typeof getUserCapabilities = getUserCapabilities;

async function viewerCanManageServerSettings(userId: string): Promise<boolean> {
  try {
    const caps = await resolveViewerCapabilities(userId);
    return caps.includes("manage_server_settings");
  } catch {
    return false;
  }
}

let pinProviderSingleton: PinChallengeProvider | undefined;

function getPinProvider(): PinChallengeProvider {
  pinProviderSingleton ??= new PinChallengeProvider();
  return pinProviderSingleton;
}

/** Test seam: avoids global `mock.module("@nautilo/trust")` pollution. */
export function __setPinProviderForTests(provider: PinChallengeProvider | undefined): void {
  pinProviderSingleton = provider;
}

/** Test seam: keeps capability projections hermetic without module mocking. */
export function __setSetupStatusCapabilityResolverForTests(
  resolver: typeof getUserCapabilities | undefined,
): void {
  resolveViewerCapabilities = resolver ?? getUserCapabilities;
}

/**
 * D125 — conservative auto-handle heuristic. True when the stored handle
 * matches what seedDefaultOwner / JIT slugify would derive from display
 * name (exact match or numeric suffix). User-chosen handles that diverge
 * from the slug return false.
 */
function isHandleAutoGenerated(name: string, handle: string | null): boolean {
  if (!handle) return false;
  const base = slugifyToHandle(name) ?? "owner";
  const normalized = handle.trim().toLowerCase();
  if (normalized === base) return true;
  const escaped = base.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  if (new RegExp(`^${escaped}\\d+$`).test(normalized)) return true;
  return new RegExp(`^${escaped}-\\d+$`).test(normalized);
}

async function resolvePasswordWasTemp(userId: string): Promise<boolean | null> {
  try {
    const sec = await getAccountSecurityRowByUserId(db, userId);
    if (!sec) return null;
    return sec.requiresPasswordChange === true;
  } catch {
    return null;
  }
}

function buildRecommendedSetupSurface(
  setupState: SetupState,
  canManageProviderKeys: boolean,
  instance: ReturnType<typeof resolveInstance>,
): { kind: RecommendedSetupSurfaceKind; url: string | null } {
  const workbenchUrl = resolvePublicWorkbenchUrl(instance);
  const serverUrl = resolvePublicServerUrl(instance);
  switch (setupState) {
    case "fresh-unclaimed":
      return { kind: "electron-onboarding", url: workbenchUrl };
    case "claimed-needs-auth":
      return { kind: "workbench-admin", url: serverUrl };
    case "server-needs-keys":
      if (canManageProviderKeys) {
        // Keep recovery on the current Workbench origin. In compiled local
        // dev, the SPA is served by serverUrl while workbenchUrl targets Vite;
        // an absolute Vite URL is rejected by the browser-safe link allowlist.
        return { kind: "workbench-admin", url: "/admin#provider-credentials" };
      }
      return { kind: "ask-admin", url: null };
    case "ready":
    default:
      return { kind: "cli", url: null };
  }
}

async function deriveSetupStateCore(args: {
  sessionUserId: string | null;
}): Promise<{
  setupState: SetupState;
  claimRequired: boolean;
  hasAdmin: boolean;
  hasClaim: boolean;
  hasLlm: boolean;
  hasVoice: boolean;
  hasSearch: boolean;
  hasConversion: boolean;
  managedByCloud: boolean;
}> {
  const db = getServerDirectDb();
  const hasClaim = await hasUnredeemedClaimInvite(db);
  const hasA = await hasClaimedOwner(db);
  // A claim row is a handoff capability, not ownership. Once the canonical
  // owner projection is true, a stale/legacy claim must never regress this
  // target to `fresh-unclaimed`.
  const claimRequired = !hasA;
  const freshUnclaimed = !hasA;

  let hasLlm = false;
  let hasVoice = false;
  let hasSearch = false;
  let hasConversion = false;
  let managedByCloud = false;
  // Guests never receive `providers`; `setupState` for them does not depend
  // on key material — skip `check()` to avoid env/vault work on every poll.
  if (args.sessionUserId) {
    // `check()` has already derived these redacted capability booleans from
    // the key report. Reuse that summary rather than exposing, re-scanning,
    // or returning provider records (which carry masked-value metadata).
    const { summary } = await check();
    hasLlm = summary.hasLlm;
    hasVoice = summary.hasVoice;
    hasSearch = summary.hasSearch;
    hasConversion = summary.hasConversion;
    managedByCloud = managedByCloudFromInstance();
  }

  let setupState: SetupState;
  if (freshUnclaimed) {
    setupState = "fresh-unclaimed";
  } else if (!args.sessionUserId) {
    setupState = "claimed-needs-auth";
  } else if (!hasLlm && !managedByCloud) {
    setupState = "server-needs-keys";
  } else {
    setupState = "ready";
  }

  return {
    setupState,
    claimRequired,
    hasAdmin: hasA,
    hasClaim,
    hasLlm,
    hasVoice,
    hasSearch,
    hasConversion,
    managedByCloud,
  };
}

export function setupStatusRoutes(app: FastifyInstance): void {
  app.get("/api/setup/status", async (request, reply) => {
    const instance = resolveInstance();
    const sessionUserId = request.sessionUserId;
    const core = await deriveSetupStateCore({ sessionUserId });
    const deployConfigConsumedAt = readDeployConfigConsumedAt(resolveNautiloRootDir());
    const defaultName = deriveDefaultServerName({
      host: resolvePublicServerUrl(instance),
      instanceId: instance.instanceId,
    });
    const resolvedServerProfile = await getServerProfile(getServerDirectDb(), {
      defaultName,
    });
    const serverProfile = buildPublicServerProfile(resolvedServerProfile, sessionUserId);

    const base = {
      instanceId: instance.instanceId,
      serverUrl: resolvePublicServerUrl(instance),
      deploymentMode: instance.deploymentMode,
      setupState: core.setupState,
      claimRequired: core.claimRequired,
      deployConfigConsumedAt,
      serverProfile,
    };

    if (!sessionUserId) {
      const recommendedSetupSurface = buildRecommendedSetupSurface(
        core.setupState,
        false,
        instance,
      );
      return reply.send({
        ...base,
        recommendedSetupSurface,
      });
    }

    const profile = await getProfile(sessionUserId);
    const viewerUser = await resolveViewerUserRow(sessionUserId);
    const canManageServerSettings =
      await viewerCanManageServerSettings(sessionUserId);
    const capabilities: readonly string[] = await resolveViewerCapabilities(sessionUserId).catch(() => []);
    const canManageProviderKeys = canManageServerSettings || capabilities.includes("manage_connection_providers");
    const canInvokeAgents = capabilities.includes("invoke_agents");
    const genieCustomized = profile?.onboardingCompleted === true;
    const byokConfigured = false;
    const pinEnrolled = await getPinProvider().isEnrolled(sessionUserId);
    const handleAutoGenerated = viewerUser
      ? isHandleAutoGenerated(viewerUser.name, viewerUser.handle)
      : false;
    const passwordWasTemp = await resolvePasswordWasTemp(sessionUserId);

    const claimInvitePathHint =
      shouldExposeClaimInvitePathHint(request) &&
      canManageServerSettings &&
      core.claimRequired
        ? join(resolveNautiloRootDir(), "claim-invite.txt")
        : null;

    return reply.send({
      ...base,
      viewer: {
        canManageServerSettings,
        canInvokeAgents,
        genieCustomized,
        byokConfigured,
        pinEnrolled,
        handleAutoGenerated,
        passwordWasTemp,
      },
      providers: {
        hasLlm: core.hasLlm,
        hasVoice: core.hasVoice,
        hasSearch: core.hasSearch,
        hasConversion: core.hasConversion,
        managedByCloud: core.managedByCloud,
      },
      recommendedSetupSurface: buildRecommendedSetupSurface(
        core.setupState,
        canManageProviderKeys,
        instance,
      ),
      claimInvitePathHint,
    });
  });

  /**
   * D112 Phase 19.1 — re-read `instance.env` from disk into the
   * running server's `process.env`, then drop managed-registry keys
   * that no longer appear on disk.
   *
   * Why this exists: `nautilo setup` runs as a separate CLI process
   * and writes provider keys to `~/.nautilo-<id>/instance.env` via
   * `config-guard.transaction`. The transaction updates the CLI's
   * own `process.env` but the running Fastify server has its own
   * (stale) `process.env` from boot time. Until this endpoint is
   * called, the server still reports "Anthropic API key not found"
   * on the very first chat turn even though the key is cleanly on
   * disk and config-guard validates it. Operators have been
   * working around it by manually restarting the server after
   * setup; this endpoint removes that step.
   *
   * Trust model (loopback / unix-socket + admin session bearer):
   *   - loopback IP or unix-socket caller (per `requestAllowsLoopbackTrust`),
   *     which covers same-host CLI ops over 127.0.0.1 and over the local
   *     `~/.nautilo/server.sock` forwarder.
   *   - `Authorization: Bearer <session>` must verify and resolve to a
   *     caller holding `manage_server_settings` (D219 — the retired
   *     `users.serverRole=admin` enum read). The post-claim redeem bearer
   *     (a Logto session token) satisfies this directly, which is how
   *     `nautilo setup` drives this endpoint right after redeem.
   *   - safe across all setupStates: even after `ready`, an operator may
   *     legitimately rotate keys via setup and want the server to pick them
   *     up without a bounce.
   *
   * D120 A5 follow-up — the gate USED to be widened to
   * `requestAllowsPrivilegedSetup` (loopback OR bootstrap-token bearer) so a
   * remote operator could rotate keys without SSH. That widening was unsound:
   * a single `Authorization` header can carry EITHER the bootstrap token
   * (satisfies the privileged-setup gate) OR the admin session bearer
   * (satisfies the `sessionUserId` + admin checks below), but not both. The
   * remote path was therefore unsatisfiable. The route is back to loopback +
   * admin-session pending the dual-auth contract design tracked in
   * ISSUE-D131.
   *
   * The reload itself is cheap — `reloadEnvAndStripRemovedRegistryKeys`
   * just calls `dotenv.config({ override: true })` and prunes
   * unmanaged-key drops. LLM clients across the codebase read
   * provider keys lazily on each request via `resolveProviderKey`
   * (D120 A1.P4 — pre-D120 a direct env read), so no client
   * re-instantiation is needed.
   */
  app.post(
    "/api/setup/reload-env",
    async (request, reply) => {
      if (!requestAllowsLoopbackTrust(request)) {
        return reply.code(403).send({ error: "loopback only" });
      }
      const userId = request.sessionUserId;
      if (!userId) {
        return reply.code(401).send({ error: "Authentication required" });
      }
      if (!(await viewerCanManageServerSettings(userId))) {
        return reply.code(403).send({ error: "admin only" });
      }
      try {
        const path = resolveDotenvPath();
        await reloadEnvAndStripRemovedRegistryKeys(path);
        return reply.send({ ok: true, path });
      } catch (e) {
        logError(
          "[setup] POST /api/setup/reload-env failed:",
          e instanceof Error ? e.stack ?? e.message : String(e),
        );
        return reply.code(500).send({ error: "Failed to reload instance.env." });
      }
    },
  );
}
