export {
  createFile,
  applyBlockStyle,
  deleteBlocks,
  deleteTable,
  deleteTableColumn,
  deleteTableRow,
  editOpenWriter,
  exportDocx,
  formatText,
  importDocx,
  indentBlocks,
  insertBlocks,
  insertTable,
  insertTableColumn,
  insertTableRow,
  inspectDocument,
  locateOpenWriterText,
  mergeTableCells,
  moveBlocks,
  outdentBlocks,
  replaceText,
  readOpenWriterRange,
  setBlockType,
  setTableCellStyle,
  splitTableCell,
} from "./src/agent-tool-handlers";
