/**
 * D103 P4d.7 — first-run state-aware probe + helper tests.
 *
 * Covers:
 *   1. Network-OK + state=fresh-unclaimed → helper resolves to "unclaimed".
 *   2. Network-OK + state=ready+viewer    → helper resolves to "authenticated".
 *   3. Network-fail (fetch throws)        → helper falls back to the
 *      documented `{ state: "ready", raw: null }` envelope so callers
 *      keep rendering instead of crashing the IPC handler.
 *   4. `humanizeFailReason("invalid-url")` returns the user-visible
 *      "Not a valid URL" string the picker shows when the URL pre-flight
 *      rejects malformed input. `humanizeFailReason` is the renderer-
 *      side mapping that turns the discriminated `UrlProbeFailReason`
 *      union into the inline error label.
 *
 * Stub strategy: `probeServerClaimStateForUrl` instantiates a
 * `NautiloApiClient` which calls `globalThis.fetch`. We swap fetch with
 * a per-test stub instead of dragging in a DI wrapper — keeps the
 * helper's public surface tested as-is, including its swallow-and-fall-
 * back-to-"ready" error path.
 */

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { probeServerClaimStateForUrl } from "../../electron/boot-setup-status";
import { humanizeFailReason } from "../../first-run/humanize-fail-reason";

const ORIGINAL_FETCH = globalThis.fetch;

function jsonResponse(body: unknown, init: ResponseInit = {}): Response {
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { "content-type": "application/json" },
    ...init,
  });
}

async function waitFor(predicate: () => boolean): Promise<void> {
  const deadline = Date.now() + 1_000;
  while (!predicate()) {
    if (Date.now() >= deadline) throw new Error("timed out waiting for setup probe transport");
    await Bun.sleep(1);
  }
}

function readySetupResponse(): Response {
  return jsonResponse({
    instanceId: "i",
    serverUrl: "http://127.0.0.1:3001",
    deploymentMode: "local-self-host",
    claimRequired: false,
    setupState: "ready",
    recommendedSetupSurface: { kind: "cli", url: null },
  });
}

afterEach(() => {
  globalThis.fetch = ORIGINAL_FETCH;
});

describe("probeServerClaimStateForUrl (D103 P4d.7)", () => {
  test("network-OK + setupState=fresh-unclaimed → state=unclaimed", async () => {
    globalThis.fetch = (async () =>
      jsonResponse({
        instanceId: "i",
        serverUrl: "http://127.0.0.1:3001",
        deploymentMode: "local-self-host",
        claimRequired: true,
        setupState: "fresh-unclaimed",
        recommendedSetupSurface: { kind: "cli", url: null },
      })) as typeof fetch;

    const result = await probeServerClaimStateForUrl("http://127.0.0.1:3001");
    expect(result.state).toBe("unclaimed");
    expect(result.raw?.setupState).toBe("fresh-unclaimed");
  });

  test("network-OK + setupState=ready + viewer present → state=authenticated", async () => {
    globalThis.fetch = (async () =>
      jsonResponse({
        instanceId: "i",
        serverUrl: "http://127.0.0.1:3001",
        deploymentMode: "local-self-host",
        claimRequired: false,
        setupState: "ready",
        viewer: {
          canManageServerSettings: false,
          genieCustomized: true,
          byokConfigured: true,
          pinEnrolled: true,
          handleAutoGenerated: false,
          passwordWasTemp: false,
        },
        recommendedSetupSurface: { kind: "workbench-admin", url: "http://127.0.0.1:3001" },
      })) as typeof fetch;

    const result = await probeServerClaimStateForUrl("http://127.0.0.1:3001");
    expect(result.state).toBe("authenticated");
    expect(result.raw?.viewer).toBeDefined();
  });

  test("network-fail (fetch throws) → falls back to state=ready, raw=null", async () => {
    globalThis.fetch = (async () => {
      throw new TypeError("Failed to fetch");
    }) as typeof fetch;

    const result = await probeServerClaimStateForUrl("http://unreachable.invalid");
    expect(result.state).toBe("ready");
    expect(result.raw).toBeNull();
  });

  test("caller cancellation aborts a stalled setup-status transport", async () => {
    let transportSignal: AbortSignal | null = null;
    let transportAborted = false;
    globalThis.fetch = ((_input: RequestInfo | URL, init?: RequestInit) =>
      new Promise<Response>((_resolve, reject) => {
        transportSignal = init?.signal ?? null;
        const onAbort = () => {
          transportAborted = true;
          reject(transportSignal?.reason);
        };
        if (transportSignal?.aborted) onAbort();
        else transportSignal?.addEventListener("abort", onAbort, { once: true });
      })) as typeof fetch;

    const controller = new AbortController();
    const probing = probeServerClaimStateForUrl(
      "http://127.0.0.1:3001",
      controller.signal,
    );
    await waitFor(() => transportSignal !== null);
    const reason = new DOMException("setup cancelled", "AbortError");
    controller.abort(reason);

    await expect(probing).rejects.toBe(reason);
    expect(transportSignal).toBe(controller.signal);
    expect(transportAborted).toBe(true);
  });

  test("a setup transport that resolves after cancellation cannot publish its late result", async () => {
    let transportStarted = false;
    let resolveTransport: ((response: Response) => void) | null = null;
    globalThis.fetch = ((_input: RequestInfo | URL, init?: RequestInit) => {
      expect(init?.signal).toBeDefined();
      transportStarted = true;
      return new Promise<Response>((resolve) => {
        resolveTransport = resolve;
      });
    }) as typeof fetch;

    const controller = new AbortController();
    const probing = probeServerClaimStateForUrl(
      "http://127.0.0.1:3001",
      controller.signal,
    );
    await waitFor(() => transportStarted);
    const reason = new DOMException("superseded", "AbortError");
    controller.abort(reason);
    resolveTransport?.(readySetupResponse());

    await expect(probing).rejects.toBe(reason);
  });
});

describe("humanizeFailReason (D103 P4d.5)", () => {
  test("invalid-url → 'Not a valid URL'", () => {
    expect(humanizeFailReason("invalid-url")).toBe("Not a valid URL");
  });

  test("each reason has a non-empty user-facing string", () => {
    const reasons = [
      "invalid-url",
      "timeout",
      "network-error",
      "tls-error",
      "bad-status",
      "not-nautilo",
    ] as const;
    for (const r of reasons) {
      expect(humanizeFailReason(r).length).toBeGreaterThan(0);
    }
  });
});

// Bind beforeEach so eslint-no-unused-vars doesn't flag the import; we
// explicitly assert the original fetch binding is restored between tests.
beforeEach(() => {
  // intentionally empty — afterEach handles restoration; this stub
  // gives the linter and contributor-readers a clear "tests are
  // hermetic" signal.
});
