import { describe, expect, test } from "bun:test";
import { ZodError } from "zod";
import {
  avatarRefSchema,
  setupStatusResponseSchema,
} from "../../src/schemas/setup-status";

const baseServerProfile = {
  name: "My Server",
  description: "A test instance",
  icon: { kind: "preset" as const, id: "server-default" },
  reviewedAt: "2026-08-10T20:00:00.000Z",
};

const baseSetupStatus = {
  instanceId: "",
  serverUrl: "http://localhost:3001",
  deploymentMode: "local-self-host" as const,
  setupState: "ready" as const,
  claimRequired: false,
  serverProfile: baseServerProfile,
};

describe("setupStatusResponseSchema", () => {
  test("parses redacted (guest) payload", () => {
    const parsed = setupStatusResponseSchema.parse({
      ...baseSetupStatus,
    });
    expect(parsed.viewer).toBeUndefined();
    expect(parsed.providers).toBeUndefined();
    expect(parsed.serverProfile).toEqual(baseServerProfile);
  });

  test("parses authenticated payload", () => {
    const parsed = setupStatusResponseSchema.parse({
      ...baseSetupStatus,
      deployConfigConsumedAt: "2026-05-13T18:00:00.000Z",
      viewer: {
        canManageServerSettings: true,
        genieCustomized: false,
        byokConfigured: false,
        pinEnrolled: false,
        handleAutoGenerated: true,
        passwordWasTemp: true,
      },
      providers: {
        hasLlm: true,
        hasVoice: true,
        hasSearch: false,
        hasConversion: true,
        managedByCloud: false,
      },
      recommendedSetupSurface: { kind: "cli", url: null },
      claimInvitePathHint: null,
    });
    expect(parsed.viewer?.canManageServerSettings).toBe(true);
    expect(parsed.providers?.hasLlm).toBe(true);
    expect(parsed.providers?.hasVoice).toBe(true);
    expect(parsed.providers?.hasSearch).toBe(false);
    expect(parsed.providers?.hasConversion).toBe(true);
    expect(parsed.deployConfigConsumedAt).toBe("2026-05-13T18:00:00.000Z");
    expect(parsed.viewer?.pinEnrolled).toBe(false);
    expect(parsed.viewer?.handleAutoGenerated).toBe(true);
    expect(parsed.viewer?.passwordWasTemp).toBe(true);
    expect(parsed.serverProfile?.name).toBe("My Server");
    expect(parsed.serverProfile?.description).toBe("A test instance");
    expect(parsed.serverProfile?.icon).toEqual({ kind: "preset", id: "server-default" });
    expect(parsed.serverProfile?.reviewedAt).toBe("2026-08-10T20:00:00.000Z");
  });

  test("preserves D125 viewer gating fields after parse", () => {
    const raw = {
      ...baseSetupStatus,
      instanceId: "inst",
      deployConfigConsumedAt: null,
      viewer: {
        canManageServerSettings: true,
        genieCustomized: false,
        byokConfigured: false,
        pinEnrolled: true,
        handleAutoGenerated: false,
        passwordWasTemp: null,
      },
    };
    const parsed = setupStatusResponseSchema.parse(raw);
    expect(parsed).toEqual(raw);
  });

  test("parses serverProfile with description omitted (members visibility)", () => {
    const parsed = setupStatusResponseSchema.parse({
      ...baseSetupStatus,
      serverProfile: {
        name: "Private Server",
        icon: { kind: "preset", id: "server-default" },
      },
    });
    expect(parsed.serverProfile?.name).toBe("Private Server");
    expect(parsed.serverProfile?.description).toBeUndefined();
  });

  test("accepts payload missing serverProfile (older / pre-D280 server)", () => {
    const { serverProfile: _omit, ...withoutProfile } = baseSetupStatus;
    const parsed = setupStatusResponseSchema.parse(withoutProfile);
    expect(parsed.serverProfile).toBeUndefined();
  });

  test("accepts older authenticated provider payloads without secondary capability booleans", () => {
    const parsed = setupStatusResponseSchema.parse({
      ...baseSetupStatus,
      providers: { hasLlm: true, managedByCloud: false },
    });
    expect(parsed.providers).toEqual({ hasLlm: true, managedByCloud: false });
  });
});

describe("avatarRefSchema", () => {
  test("accepts preset icon", () => {
    expect(avatarRefSchema.parse({ kind: "preset", id: "server-default" })).toEqual({
      kind: "preset",
      id: "server-default",
    });
  });

  test("accepts uploaded icon", () => {
    expect(avatarRefSchema.parse({ kind: "uploaded", blobId: "blob-1" })).toEqual({
      kind: "uploaded",
      blobId: "blob-1",
    });
  });

  test("accepts generated icon", () => {
    expect(avatarRefSchema.parse({ kind: "generated", blobId: "blob-2" })).toEqual({
      kind: "generated",
      blobId: "blob-2",
    });
  });

  test("rejects malformed preset icon missing id", () => {
    expect(() => avatarRefSchema.parse({ kind: "preset" })).toThrow(ZodError);
  });
});
