import { readFile, writeFile } from "node:fs/promises";

import {
  APPLICATION_CATALOGUE_MANIFEST_V1,
  type ApplicationCatalogueManifestEntryV1,
} from "../../apps/workbench/src/lib/application-catalogue-manifest";
import {
  APPLICATION_CATALOGUE_TARGET_IDS_V1,
  GENERATED_APPLICATION_CATALOGUE_V1,
} from "../../packages/types/src/generated/application-catalogue-v1";

function assertFiniteManifest(entries: readonly ApplicationCatalogueManifestEntryV1[]): void {
  const ids = entries.map((entry) => entry.target);
  if (new Set(ids).size !== ids.length) throw new Error("Application catalogue manifest contains duplicate target IDs");
  if (ids.some((id) => !/^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)*$/u.test(id))) {
    throw new Error("Application catalogue manifest contains an invalid target ID");
  }
}

export function applicationCatalogueMetadataFromManifest(
  entries: readonly ApplicationCatalogueManifestEntryV1[] = APPLICATION_CATALOGUE_MANIFEST_V1,
) {
  assertFiniteManifest(entries);
  return entries.map(({ target, label, menuPath, description, discoveryTerms }) => ({
    target, label, menuPath: [...menuPath], description, discoveryTerms: [...discoveryTerms],
  }));
}

/** Stable renderer for the checked-in artifact; tests never invoke write mode. */
export function renderApplicationCatalogueV1(): string {
  const metadata = applicationCatalogueMetadataFromManifest();
  const ids = metadata.map((entry) => entry.target);
  return `/**\n * GENERATED by dev/scripts/generate-application-catalogue.ts. Do not edit.\n * This artifact contains metadata only: never add routes, selectors, handlers,\n * capabilities, or mutations.\n */\nexport const APPLICATION_CATALOGUE_TARGET_IDS_V1 = ${JSON.stringify(ids, null, 2)} as const;\n\nconst GENERATED_APPLICATION_CATALOGUE_METADATA_V1 = ${JSON.stringify(metadata, null, 2)} as const;\n\nexport const GENERATED_APPLICATION_CATALOGUE_V1 = {\n  version: 1,\n  catalogueVersion: "2026-09-05.1",\n  publishedAt: "2026-09-05T00:00:00.000Z",\n  provenance: "bundled",\n  targets: GENERATED_APPLICATION_CATALOGUE_METADATA_V1,\n} as const;\n`;
}

/** Fail-closed drift check used by CI and tests; it never writes. */
export async function assertGeneratedApplicationCatalogueIsCurrent(): Promise<void> {
  const expected = applicationCatalogueMetadataFromManifest();
  const actual = GENERATED_APPLICATION_CATALOGUE_V1.targets.map((entry) => ({
    ...entry, menuPath: [...entry.menuPath], discoveryTerms: [...entry.discoveryTerms],
  }));
  if (JSON.stringify(expected) !== JSON.stringify(actual)) {
    throw new Error("Generated application catalogue is stale; run the deterministic generator before committing");
  }
  if (JSON.stringify(expected.map((entry) => entry.target)) !== JSON.stringify(APPLICATION_CATALOGUE_TARGET_IDS_V1)) {
    throw new Error("Generated application catalogue target IDs drift from metadata");
  }
  const artifact = await readFile(
    new URL("../../packages/types/src/generated/application-catalogue-v1.ts", import.meta.url),
    "utf8",
  );
  if (artifact !== renderApplicationCatalogueV1()) {
    throw new Error("Generated application catalogue bytes are stale; run the generator with --write before committing");
  }
}

if (import.meta.main) {
  if (process.argv.includes("--write")) {
    await writeFile(
      new URL("../../packages/types/src/generated/application-catalogue-v1.ts", import.meta.url),
      renderApplicationCatalogueV1(),
      "utf8",
    );
    process.stdout.write("Application catalogue generated artifact written.\n");
  } else {
    await assertGeneratedApplicationCatalogueIsCurrent();
    process.stdout.write("Application catalogue generated artifact is current.\n");
  }
}
