import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

type FaceSpec = {
  constant: string;
  familyConstant: string;
  family: string;
  label: string;
  weight: 400 | 700;
  source: string[];
  sha256: string;
};

const REPOSITORY_ROOT = join(import.meta.dirname, "..", "..", "..", "..");
const OUTPUT_PATH = join(import.meta.dirname, "..", "src", "bundled-fonts.ts");
const FACES: readonly FaceSpec[] = [
  {
    constant: "SANS_REGULAR_BASE64",
    familyConstant: "DESIGN_BUNDLED_FONT_FAMILY",
    family: "Nautilo Noto Sans",
    label: "Noto Sans",
    weight: 400,
    source: ["packages", "fonts", "assets", "core", "sans", "NotoSans-Regular.ttf"],
    sha256: "b85c38ecea8a7cfb39c24e395a4007474fa5a4fc864f6ee33309eb4948d232d5",
  },
  {
    constant: "SANS_BOLD_BASE64",
    familyConstant: "DESIGN_BUNDLED_FONT_FAMILY",
    family: "Nautilo Noto Sans",
    label: "Noto Sans",
    weight: 700,
    source: ["packages", "fonts", "assets", "core", "sans", "NotoSans-Bold.ttf"],
    sha256: "c976e4b1b99edc88775377fcc21692ca4bfa46b6d6ca6522bfda505b28ff9d6a",
  },
  {
    constant: "SERIF_REGULAR_BASE64",
    familyConstant: "DESIGN_BUNDLED_SERIF_FONT_FAMILY",
    family: "Nautilo Noto Serif",
    label: "Noto Serif",
    weight: 400,
    source: ["packages", "fonts", "assets", "core", "serif", "NotoSerif-Regular.ttf"],
    sha256: "c8f669ceb2c9c60ccf55198b305e08a997ffca79a38cc7eeb551e643cbe66505",
  },
  {
    constant: "MONO_REGULAR_BASE64",
    familyConstant: "DESIGN_BUNDLED_MONO_FONT_FAMILY",
    family: "Nautilo Noto Sans Mono",
    label: "Noto Sans Mono",
    weight: 400,
    source: ["packages", "fonts", "assets", "core", "mono", "NotoSansMono-Regular.ttf"],
    sha256: "d9e2b23d19f8230be7146f409a52b1d23117e635e28f2e2892cf91b7382f325b",
  },
] as const;

function chunks(value: string): string {
  const lines: string[] = [];
  for (let offset = 0; offset < value.length; offset += 120) {
    lines.push(`  ${JSON.stringify(value.slice(offset, offset + 120))},`);
  }
  return `[\n${lines.join("\n")}\n].join("")`;
}

export async function generateBundledFontsSource(): Promise<string> {
  const loaded = await Promise.all(FACES.map(async (face) => {
    const sourcePath = join(REPOSITORY_ROOT, ...face.source);
    const bytes = await readFile(sourcePath);
    const sha256 = createHash("sha256").update(bytes).digest("hex");
    if (sha256 !== face.sha256) {
      throw new Error(`${face.source.join("/")} has SHA-256 ${sha256}; expected ${face.sha256}.`);
    }
    return { ...face, sourcePath: face.source.join("/"), bytes, base64: bytes.toString("base64") };
  }));
  const families = [...new Map(loaded.map((face) => [face.family, face])).values()];
  const constants = loaded.map((face) =>
    `const ${face.constant} = ${chunks(face.base64)};`).join("\n\n");
  const catalogue = families.map((family) => {
    const faces = loaded.filter((face) => face.family === family.family);
    return `  {\n    family: ${family.familyConstant},\n    label: ${JSON.stringify(family.label)},\n    weights: [${faces.map((face) => face.weight).join(", ")}],\n    faces: [\n${faces.map((face) => `      { weight: ${face.weight}, sourcePath: ${JSON.stringify(face.sourcePath)}, sha256: ${JSON.stringify(face.sha256)}, byteLength: ${face.bytes.byteLength} },`).join("\n")}\n    ],\n  },`;
  }).join("\n");
  const faceRows = loaded.map((face) =>
    `  [designBundledFontFaceKey(${face.familyConstant}, ${face.weight}), { family: ${face.familyConstant}, weight: ${face.weight}, base64: ${face.constant} }],`).join("\n");

  return `// eslint-disable-next-line @typescript-eslint/triple-slash-reference -- Server consumers also need this app-local ambient declaration.\n/// <reference path="./fontkit.d.ts" />\n/**\n * GENERATED by scripts/generate-bundled-fonts.ts from the canonical assets in\n * packages/fonts. Do not edit this file by hand. The generator verifies every\n * complete font face by SHA-256 before embedding it for browser and server use.\n */\n\nimport { create as createFont } from "fontkit";\n\nexport type DesignFont = {\n  unitsPerEm: number;\n  hasGlyphForCodePoint(codePoint: number): boolean;\n  layout(text: string): {\n    glyphs: Array<{ path: { transform(a: number, b: number, c: number, d: number, e: number, f: number): { toSVG(): string; bbox: { minX: number; minY: number; maxX: number; maxY: number } } } }>;\n    positions: Array<{ xAdvance: number; yAdvance: number; xOffset: number; yOffset: number }>;\n  };\n};\n\ntype FontFactory = (buffer: Uint8Array) => DesignFont;\nconst create = createFont as FontFactory;\n\nexport const DESIGN_BUNDLED_FONT_FAMILY = "Nautilo Noto Sans";\nexport const DESIGN_BUNDLED_SERIF_FONT_FAMILY = "Nautilo Noto Serif";\nexport const DESIGN_BUNDLED_MONO_FONT_FAMILY = "Nautilo Noto Sans Mono";\nexport type DesignBundledFontFamily =\n  | typeof DESIGN_BUNDLED_FONT_FAMILY\n  | typeof DESIGN_BUNDLED_SERIF_FONT_FAMILY\n  | typeof DESIGN_BUNDLED_MONO_FONT_FAMILY;\nexport type DesignBundledFontWeight = 400 | 700;\nexport type DesignBundledFontFaceKey = \`\${DesignBundledFontFamily}::\${DesignBundledFontWeight}\`;\n\nexport const DESIGN_BUNDLED_FONT_CATALOG = [\n${catalogue}\n] as const;\n\nexport const DESIGN_BUNDLED_FONT_FAMILIES: readonly DesignBundledFontFamily[] =\n  DESIGN_BUNDLED_FONT_CATALOG.map((entry) => entry.family);\n\n${constants}\n\nconst BASE64_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";\n\nfunction decodeBase64(source: string): Uint8Array {\n  if (source.length % 4 !== 0) throw new Error("Bundled font data is malformed.");\n  const padding = source.endsWith("==") ? 2 : source.endsWith("=") ? 1 : 0;\n  const bytes = new Uint8Array(source.length / 4 * 3 - padding);\n  let write = 0;\n  for (let offset = 0; offset < source.length; offset += 4) {\n    const a = BASE64_ALPHABET.indexOf(source[offset]!);\n    const b = BASE64_ALPHABET.indexOf(source[offset + 1]!);\n    const c = source[offset + 2] === "=" ? 0 : BASE64_ALPHABET.indexOf(source[offset + 2]!);\n    const d = source[offset + 3] === "=" ? 0 : BASE64_ALPHABET.indexOf(source[offset + 3]!);\n    if (a < 0 || b < 0 || c < 0 || d < 0) throw new Error("Bundled font data is malformed.");\n    const value = a << 18 | b << 12 | c << 6 | d;\n    if (write < bytes.length) bytes[write++] = value >> 16 & 255;\n    if (write < bytes.length) bytes[write++] = value >> 8 & 255;\n    if (write < bytes.length) bytes[write++] = value & 255;\n  }\n  return bytes;\n}\n\ntype FaceData = { family: DesignBundledFontFamily; weight: DesignBundledFontWeight; base64: string };\n\nexport function designBundledFontFaceKey(\n  family: DesignBundledFontFamily,\n  weight: DesignBundledFontWeight,\n): DesignBundledFontFaceKey {\n  return \`\${family}::\${weight}\`;\n}\n\nconst FACE_DATA = new Map<DesignBundledFontFaceKey, FaceData>([\n${faceRows}\n]);\nconst FONT_CACHE = new Map<DesignBundledFontFaceKey, DesignFont>();\n\nexport function isDesignBundledFontFamily(value: string): value is DesignBundledFontFamily {\n  return DESIGN_BUNDLED_FONT_FAMILIES.includes(value as DesignBundledFontFamily);\n}\n\nexport function designBundledFontWeights(\n  family: DesignBundledFontFamily,\n): readonly DesignBundledFontWeight[] {\n  return DESIGN_BUNDLED_FONT_CATALOG.find((entry) => entry.family === family)?.weights ?? [];\n}\n\nexport function designBundledFontForStyle(\n  family: DesignBundledFontFamily,\n  weight: DesignBundledFontWeight,\n): DesignFont | null {\n  const key = designBundledFontFaceKey(family, weight);\n  const data = FACE_DATA.get(key);\n  if (!data) return null;\n  const cached = FONT_CACHE.get(key);\n  if (cached) return cached;\n  const font = create(decodeBase64(data.base64));\n  FONT_CACHE.set(key, font);\n  return font;\n}\n\n/** Backward-compatible Sans face lookup. */\nexport function designBundledFont(weight: 400 | 700): DesignFont {\n  const font = designBundledFontForStyle(DESIGN_BUNDLED_FONT_FAMILY, weight);\n  if (!font) throw new Error(\`Bundled Sans weight \${weight} is unavailable.\`);\n  return font;\n}\n\n/**\n * Embed each complete canonical face used by the document exactly once. Numeric\n * keys remain accepted for the former Sans-only API.\n */\nexport function designBundledFontFaceCss(\n  usage: ReadonlyMap<DesignBundledFontFaceKey | 400 | 700, string>,\n): string {\n  const used = new Set<DesignBundledFontFaceKey>();\n  for (const [key, text] of usage) {\n    if (!text.length) continue;\n    used.add(typeof key === "number"\n      ? designBundledFontFaceKey(DESIGN_BUNDLED_FONT_FAMILY, key)\n      : key);\n  }\n  return [...FACE_DATA]\n    .filter(([key]) => used.has(key))\n    .map(([, face]) => \`@font-face{font-family:\${JSON.stringify(face.family)};font-style:normal;font-weight:\${face.weight};src:url(data:font/ttf;base64,\${face.base64}) format("truetype")}\`)\n    .join("");\n}\n`;
}

if (import.meta.main) {
  const generated = await generateBundledFontsSource();
  if (process.argv.includes("--check")) {
    const current = await readFile(OUTPUT_PATH, "utf8").catch(() => "");
    if (current !== generated) {
      console.error("src/bundled-fonts.ts is stale; run bun scripts/generate-bundled-fonts.ts.");
      process.exitCode = 1;
    }
  } else {
    await writeFile(OUTPUT_PATH, generated);
  }
}
