export const STENOGRAPHER_MESSAGE_TRIGGER = 5;
export const STENOGRAPHER_SILENCE_MS = 2 * 60 * 1_000;
export const STENOGRAPHER_HEALTH_WINDOW_MS = 24 * 60 * 60 * 1_000;
export const STENOGRAPHER_HEALTH_GRACE_MS = 60 * 1_000;
export const STENOGRAPHER_HEALTH_DEGRADED_OVERDUE_MS = 5 * 60 * 1_000;
export const STENOGRAPHER_HEALTH_DEGRADED_FAILURES = 3;
export const STENOGRAPHER_HEALTH_RECENT_FAILURES = 5;
