/**
 * Provider-neutral, sealed streaming recovery container.
 *
 * This is deliberately only a byte container. It knows nothing about S3,
 * Railway, Docker, or a database. Callers stream each logical member into the
 * writer and stream authenticated plaintext into a staging sink while reading;
 * callers must not promote staged data until `readPortableRecovery()` resolves.
 */

import { createHash } from "node:crypto";
import { xchacha20poly1305 } from "@noble/ciphers/chacha";

export const PORTABLE_RECOVERY_FORMAT = "nautilo-recovery-v1" as const;
export const PORTABLE_RECOVERY_VERSION = 1 as const;
const MAX_PORTABLE_RECOVERY_CHUNK_BYTES = 8 * 1024 * 1024;

const NONCE_SEED_BYTES = 32;
const NONCE_BYTES = 24;
const TAG_BYTES = 16;
const MAX_TERMINAL_MANIFEST_BYTES = 1024 * 1024;
const MAX_HEADER_BYTES = 1024;
const MAX_SOURCE_RELEASE_BYTES = 512;
const MAX_TOTAL_CHUNKS = 0xffff_ffff;
const MAGIC = new TextEncoder().encode("nautilo-recovery-v1\\n");
const TEXT_ENCODER = new TextEncoder();
const TEXT_DECODER = new TextDecoder("utf-8", { fatal: true });

export const PORTABLE_RECOVERY_MEMBERS = [
  "app-postgres.dump",
  "logto-postgres.dump",
  "artifacts.tar",
  "media.tar",
  "apps.tar",
] as const;

export type PortableRecoveryMemberName = (typeof PORTABLE_RECOVERY_MEMBERS)[number];

export class PortableRecoveryError extends Error {
  public constructor(
    public readonly code:
      | "INVALID_INPUT"
      | "INVALID_FORMAT"
      | "TRUNCATED"
      | "NONCANONICAL_FRAME_ORDER"
      | "AUTH_FAILED"
      | "INTEGRITY_FAILED"
      | "RECEIPT_MISMATCH",
    message: string,
  ) {
    super(message);
    this.name = "PortableRecoveryError";
  }
}

export interface PortableRecoveryMemberSource {
  readonly name: PortableRecoveryMemberName;
  readonly chunks: AsyncIterable<Uint8Array>;
}

export interface WritePortableRecoveryInput {
  /** Exactly 32 random bytes generated by the caller's CSPRNG, once per bundle. */
  readonly nonceSeed: Uint8Array;
  readonly key: Uint8Array;
  readonly sourceRelease: string;
  /** Every allowlisted member, in `PORTABLE_RECOVERY_MEMBERS` order. */
  readonly members: readonly PortableRecoveryMemberSource[];
  readonly chunkBytes?: number;
}

export interface PortableRecoveryReceipt {
  readonly ciphertextSha256: string;
  readonly ciphertextBytes: number;
}

export interface PortableRecoveryMemberManifest {
  readonly name: PortableRecoveryMemberName;
  readonly sha256: string;
  readonly plaintextBytes: number;
  readonly chunks: number;
}

export interface PortableRecoveryManifest {
  readonly format: typeof PORTABLE_RECOVERY_FORMAT;
  readonly version: typeof PORTABLE_RECOVERY_VERSION;
  readonly sourceRelease: string;
  readonly totalChunks: number;
  /** Digest and count of every container byte before the encrypted terminal frame. */
  readonly payloadCiphertextSha256: string;
  readonly payloadCiphertextBytes: number;
  readonly members: readonly PortableRecoveryMemberManifest[];
}

export interface PortableRecoveryWriter {
  /** Consume this iterable to write the container. Completion resolves only at EOF. */
  readonly stream: AsyncIterable<Uint8Array>;
  readonly completion: Promise<PortableRecoveryReceipt>;
}

export interface ReadPortableRecoveryInput {
  readonly source: AsyncIterable<Uint8Array>;
  readonly key: Uint8Array;
  /** Optional receipt from the writer or object store; when supplied both fields are required. */
  readonly expectedReceipt?: PortableRecoveryReceipt;
  /** Authenticated plaintext goes to a staging sink. Do not promote it before this call resolves. */
  readonly onChunk: (chunk: {
    readonly member: PortableRecoveryMemberName;
    readonly ordinal: number;
    readonly plaintext: Uint8Array;
  }) => void | Promise<void>;
}

export interface PortableRecoveryReadResult {
  readonly manifest: PortableRecoveryManifest;
  readonly receipt: PortableRecoveryReceipt;
}

interface PublicHeader {
  readonly format: typeof PORTABLE_RECOVERY_FORMAT;
  readonly nonceSeed: string;
  readonly version: typeof PORTABLE_RECOVERY_VERSION;
}

interface Deferred<T> {
  readonly promise: Promise<T>;
  resolve(value: T): void;
  reject(reason: unknown): void;
}

function deferred<T>(): Deferred<T> {
  let resolve!: (value: T) => void;
  let reject!: (reason: unknown) => void;
  const promise = new Promise<T>((resolveInner, rejectInner) => {
    resolve = resolveInner;
    reject = rejectInner;
  });
  // A caller is expected to observe `completion`; this prevents an abandoned
  // stream from becoming an unrelated unhandled-rejection process failure.
  void promise.catch(() => undefined);
  return { promise, resolve, reject };
}

function fail(code: PortableRecoveryError["code"], message: string): never {
  throw new PortableRecoveryError(code, message);
}

function u32be(value: number): Uint8Array {
  if (!Number.isInteger(value) || value < 0 || value > MAX_TOTAL_CHUNKS) {
    fail("INVALID_INPUT", "unsigned 32-bit value is out of bounds");
  }
  const bytes = new Uint8Array(4);
  new DataView(bytes.buffer).setUint32(0, value, false);
  return bytes;
}

function readU32(bytes: Uint8Array): number {
  return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getUint32(0, false);
}

function concat(parts: readonly Uint8Array[]): Uint8Array {
  const bytes = parts.reduce((total, part) => total + part.byteLength, 0);
  const result = new Uint8Array(bytes);
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.byteLength;
  }
  return result;
}

function toBase64Url(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64url");
}

function fromBase64Url(value: string): Uint8Array {
  if (!/^[A-Za-z0-9_-]+$/.test(value)) fail("INVALID_FORMAT", "nonce seed is not canonical base64url");
  const bytes = Uint8Array.from(Buffer.from(value, "base64url"));
  if (toBase64Url(bytes) !== value) fail("INVALID_FORMAT", "nonce seed is not canonical base64url");
  return bytes;
}

function equalBytes(left: Uint8Array, right: Uint8Array): boolean {
  if (left.byteLength !== right.byteLength) return false;
  let difference = 0;
  for (let index = 0; index < left.byteLength; index += 1) difference |= left[index]! ^ right[index]!;
  return difference === 0;
}

function validateKey(key: Uint8Array): void {
  if (!(key instanceof Uint8Array) || key.byteLength !== 32) fail("INVALID_INPUT", "recovery key must be exactly 32 bytes");
}

function validateNonceSeed(seed: Uint8Array): void {
  if (!(seed instanceof Uint8Array) || seed.byteLength !== NONCE_SEED_BYTES) {
    fail("INVALID_INPUT", `nonce seed must be exactly ${NONCE_SEED_BYTES} bytes`);
  }
}

function validateChunkBytes(value: number | undefined): number {
  const chunkBytes = value ?? MAX_PORTABLE_RECOVERY_CHUNK_BYTES;
  if (!Number.isInteger(chunkBytes) || chunkBytes < 1 || chunkBytes > MAX_PORTABLE_RECOVERY_CHUNK_BYTES) {
    fail("INVALID_INPUT", `chunkBytes must be an integer in [1, ${MAX_PORTABLE_RECOVERY_CHUNK_BYTES}]`);
  }
  return chunkBytes;
}

function validateSourceRelease(value: string): void {
  if (typeof value !== "string" || value.length === 0 || TEXT_ENCODER.encode(value).byteLength > MAX_SOURCE_RELEASE_BYTES) {
    fail("INVALID_INPUT", "sourceRelease must be a non-empty bounded string");
  }
}

function validateMemberSources(members: readonly PortableRecoveryMemberSource[]): void {
  if (members.length !== PORTABLE_RECOVERY_MEMBERS.length) fail("INVALID_INPUT", "all fixed recovery members are required");
  for (let index = 0; index < PORTABLE_RECOVERY_MEMBERS.length; index += 1) {
    const member = members[index];
    if (member === undefined || member.name !== PORTABLE_RECOVERY_MEMBERS[index] || member.chunks == null || typeof member.chunks[Symbol.asyncIterator] !== "function") {
      fail("INVALID_INPUT", "recovery members must be complete, unique, and in canonical order");
    }
  }
}

/** Domain-separated nonce derived from random bundle seed + member + ordinal. */
function derivePortableRecoveryNonce(input: {
  readonly nonceSeed: Uint8Array;
  readonly memberIndex: number;
  readonly ordinal: number;
  readonly terminal: boolean;
}): Uint8Array {
  validateNonceSeed(input.nonceSeed);
  if (!Number.isInteger(input.memberIndex) || input.memberIndex < 0 || input.memberIndex > 0xff) fail("INVALID_INPUT", "invalid member index");
  const digest = createHash("sha256")
    .update(TEXT_ENCODER.encode(`${PORTABLE_RECOVERY_FORMAT}\\0nonce\\0`))
    .update(input.nonceSeed)
    .update(Uint8Array.of(input.memberIndex))
    .update(u32be(input.ordinal))
    .update(Uint8Array.of(input.terminal ? 1 : 0))
    .digest();
  return Uint8Array.from(digest.subarray(0, NONCE_BYTES));
}

function aad(input: { member: string; ordinal: number; plaintextBytes: number; terminal: boolean }): Uint8Array {
  // The fixed property order is itself part of the format's canonical encoding.
  return TEXT_ENCODER.encode(JSON.stringify({
    final: input.terminal,
    format: PORTABLE_RECOVERY_FORMAT,
    length: input.plaintextBytes,
    member: input.member,
    ordinal: input.ordinal,
    version: PORTABLE_RECOVERY_VERSION,
  }));
}

function encrypt(key: Uint8Array, nonce: Uint8Array, associatedData: Uint8Array, plaintext: Uint8Array): Uint8Array {
  return xchacha20poly1305(key, nonce, associatedData).encrypt(plaintext);
}

function decrypt(key: Uint8Array, nonce: Uint8Array, associatedData: Uint8Array, ciphertext: Uint8Array): Uint8Array {
  try {
    return xchacha20poly1305(key, nonce, associatedData).decrypt(ciphertext);
  } catch {
    fail("AUTH_FAILED", "recovery frame authentication failed");
  }
}

function dataFrame(memberIndex: number, ordinal: number, plaintextBytes: number, ciphertext: Uint8Array): Uint8Array {
  return concat([
    Uint8Array.of(1, memberIndex),
    u32be(ordinal),
    u32be(plaintextBytes),
    u32be(ciphertext.byteLength),
    ciphertext,
  ]);
}

function terminalFrame(ordinal: number, plaintextBytes: number, ciphertext: Uint8Array): Uint8Array {
  return concat([
    Uint8Array.of(2, 0xff),
    u32be(ordinal),
    u32be(plaintextBytes),
    u32be(ciphertext.byteLength),
    ciphertext,
  ]);
}

async function* fixedChunks(source: AsyncIterable<Uint8Array>, chunkBytes: number): AsyncIterable<Uint8Array> {
  let pending: Uint8Array | undefined;
  for await (const value of source) {
    if (!(value instanceof Uint8Array)) fail("INVALID_INPUT", "member source yielded a non-byte chunk");
    let offset = 0;
    if (pending !== undefined) {
      const take = Math.min(chunkBytes - pending.byteLength, value.byteLength);
      const merged = new Uint8Array(pending.byteLength + take);
      merged.set(pending);
      merged.set(value.subarray(0, take), pending.byteLength);
      offset = take;
      if (merged.byteLength === chunkBytes) {
        yield merged;
        pending = undefined;
      } else {
        pending = merged;
        continue;
      }
    }
    while (value.byteLength - offset >= chunkBytes) {
      yield value.subarray(offset, offset + chunkBytes);
      offset += chunkBytes;
    }
    if (offset < value.byteLength) pending = value.subarray(offset);
  }
  if (pending !== undefined && pending.byteLength > 0) yield pending;
}

function manifestBytes(manifest: PortableRecoveryManifest): Uint8Array {
  return TEXT_ENCODER.encode(JSON.stringify({
    format: manifest.format,
    members: manifest.members.map((member) => ({
      chunks: member.chunks,
      name: member.name,
      plaintextBytes: member.plaintextBytes,
      sha256: member.sha256,
    })),
    payloadCiphertextBytes: manifest.payloadCiphertextBytes,
    payloadCiphertextSha256: manifest.payloadCiphertextSha256,
    sourceRelease: manifest.sourceRelease,
    totalChunks: manifest.totalChunks,
    version: manifest.version,
  }));
}

/**
 * Create a sealed recovery stream. Framing retains a bounded small multiple of
 * `chunkBytes` (plaintext, ciphertext, and frame), never a whole member or
 * bundle in memory.
 */
export function writePortableRecovery(input: WritePortableRecoveryInput): PortableRecoveryWriter {
  validateKey(input.key);
  validateNonceSeed(input.nonceSeed);
  validateSourceRelease(input.sourceRelease);
  validateMemberSources(input.members);
  // Construction is the trust boundary: callers can retain and mutate their
  // input objects while the returned stream is consumed. Snapshot every value
  // that affects framing or cryptography before exposing that asynchronous API.
  const key = Uint8Array.from(input.key);
  const nonceSeed = Uint8Array.from(input.nonceSeed);
  const sourceRelease = input.sourceRelease;
  const memberSources = input.members.map((member) => ({ name: member.name, chunks: member.chunks }));
  const chunkBytes = validateChunkBytes(input.chunkBytes);
  const done = deferred<PortableRecoveryReceipt>();

  async function* stream(): AsyncIterable<Uint8Array> {
    let completed = false;
    try {
      const header: PublicHeader = {
        format: PORTABLE_RECOVERY_FORMAT,
        nonceSeed: toBase64Url(nonceSeed),
        version: PORTABLE_RECOVERY_VERSION,
      };
      const headerBytes = TEXT_ENCODER.encode(JSON.stringify(header));
      const headerFrame = concat([MAGIC, u32be(headerBytes.byteLength), headerBytes]);
      const digest = createHash("sha256");
      let ciphertextBytes = 0;
      const emit = (bytes: Uint8Array): Uint8Array => {
        digest.update(bytes);
        ciphertextBytes += bytes.byteLength;
        return bytes;
      };

      yield emit(headerFrame);
      const members: PortableRecoveryMemberManifest[] = [];
      let totalChunks = 0;
      for (let memberIndex = 0; memberIndex < memberSources.length; memberIndex += 1) {
        const member = memberSources[memberIndex]!;
        const memberDigest = createHash("sha256");
        let plaintextBytes = 0;
        let chunks = 0;
        for await (const plaintext of fixedChunks(member.chunks, chunkBytes)) {
          if (plaintext.byteLength === 0 || plaintext.byteLength > chunkBytes) fail("INVALID_INPUT", "invalid plaintext chunk size");
          if (chunks > MAX_TOTAL_CHUNKS || totalChunks > MAX_TOTAL_CHUNKS) fail("INVALID_INPUT", "too many recovery chunks");
          memberDigest.update(plaintext);
          plaintextBytes += plaintext.byteLength;
          const nonce = derivePortableRecoveryNonce({ nonceSeed, memberIndex, ordinal: chunks, terminal: false });
          const ciphertext = encrypt(key, nonce, aad({ member: member.name, ordinal: chunks, plaintextBytes: plaintext.byteLength, terminal: false }), plaintext);
          yield emit(dataFrame(memberIndex, chunks, plaintext.byteLength, ciphertext));
          chunks += 1;
          totalChunks += 1;
        }
        members.push({
          name: member.name,
          sha256: memberDigest.digest("hex"),
          plaintextBytes,
          chunks,
        });
      }

      const preTerminalDigest = digest.copy().digest("hex");
      const manifest: PortableRecoveryManifest = {
        format: PORTABLE_RECOVERY_FORMAT,
        version: PORTABLE_RECOVERY_VERSION,
        sourceRelease,
        totalChunks,
        payloadCiphertextSha256: preTerminalDigest,
        payloadCiphertextBytes: ciphertextBytes,
        members,
      };
      const plaintextManifest = manifestBytes(manifest);
      if (plaintextManifest.byteLength > MAX_TERMINAL_MANIFEST_BYTES) fail("INVALID_INPUT", "terminal manifest exceeds its bound");
      const terminalNonce = derivePortableRecoveryNonce({ nonceSeed, memberIndex: 0xff, ordinal: totalChunks, terminal: true });
      const encryptedManifest = encrypt(
        key,
        terminalNonce,
        aad({ member: "terminal-manifest", ordinal: totalChunks, plaintextBytes: plaintextManifest.byteLength, terminal: true }),
        plaintextManifest,
      );
      yield emit(terminalFrame(totalChunks, plaintextManifest.byteLength, encryptedManifest));
      const receipt = { ciphertextSha256: digest.digest("hex"), ciphertextBytes };
      completed = true;
      done.resolve(receipt);
    } catch (error) {
      done.reject(error);
      throw error;
    } finally {
      if (!completed) done.reject(new PortableRecoveryError("TRUNCATED", "recovery writer stream ended before final manifest"));
    }
  }

  return { stream: stream(), completion: done.promise };
}

class ByteReader {
  private readonly iterator: AsyncIterator<Uint8Array>;
  private current: Uint8Array<ArrayBufferLike> = new Uint8Array(0);
  private offset = 0;

  public constructor(source: AsyncIterable<Uint8Array>, private readonly digest: ReturnType<typeof createHash>, private readonly count: { value: number }) {
    this.iterator = source[Symbol.asyncIterator]();
  }

  private async fill(): Promise<boolean> {
    while (this.offset === this.current.byteLength) {
      const next = await this.iterator.next();
      if (next.done) return false;
      if (!(next.value instanceof Uint8Array)) fail("INVALID_FORMAT", "container source yielded non-byte data");
      // Keep the transport's bounded chunk by reference; copying here could
      // accidentally materialize a whole object when an adapter batches reads.
      this.current = next.value;
      this.offset = 0;
    }
    return true;
  }

  public async exact(bytes: number): Promise<Uint8Array> {
    if (!Number.isInteger(bytes) || bytes < 0) fail("INVALID_FORMAT", "invalid frame length");
    const result = new Uint8Array(bytes);
    let writeOffset = 0;
    while (writeOffset < bytes) {
      if (!(await this.fill())) fail("TRUNCATED", "container ended mid-frame");
      const take = Math.min(bytes - writeOffset, this.current.byteLength - this.offset);
      const slice = this.current.subarray(this.offset, this.offset + take);
      result.set(slice, writeOffset);
      this.digest.update(slice);
      this.count.value += take;
      this.offset += take;
      writeOffset += take;
    }
    return result;
  }

  public async byte(): Promise<number> {
    return (await this.exact(1))[0]!;
  }

  public async assertEnd(): Promise<void> {
    if (this.offset !== this.current.byteLength || await this.fill()) {
      fail("NONCANONICAL_FRAME_ORDER", "container has bytes after terminal manifest");
    }
  }
}

function parseCanonicalHeader(bytes: Uint8Array): Uint8Array {
  let parsed: unknown;
  try {
    parsed = JSON.parse(TEXT_DECODER.decode(bytes));
  } catch {
    fail("INVALID_FORMAT", "container header is not valid UTF-8 JSON");
  }
  if (!isObject(parsed) || parsed["format"] !== PORTABLE_RECOVERY_FORMAT || parsed["version"] !== PORTABLE_RECOVERY_VERSION || typeof parsed["nonceSeed"] !== "string") {
    fail("INVALID_FORMAT", "container header does not match nautilo-recovery-v1");
  }
  const header: PublicHeader = { format: PORTABLE_RECOVERY_FORMAT, nonceSeed: parsed["nonceSeed"], version: PORTABLE_RECOVERY_VERSION };
  if (TEXT_DECODER.decode(bytes) !== JSON.stringify(header)) fail("INVALID_FORMAT", "container header is not canonical");
  const nonceSeed = fromBase64Url(header.nonceSeed);
  if (nonceSeed.byteLength !== NONCE_SEED_BYTES) fail("INVALID_FORMAT", `nonce seed must be exactly ${NONCE_SEED_BYTES} bytes`);
  return nonceSeed;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isUnknownArray(value: unknown): value is unknown[] {
  return Array.isArray(value);
}

function parseManifest(bytes: Uint8Array): PortableRecoveryManifest {
  let parsed: unknown;
  try {
    parsed = JSON.parse(TEXT_DECODER.decode(bytes));
  } catch {
    fail("INTEGRITY_FAILED", "terminal manifest is not valid UTF-8 JSON");
  }
  if (!isObject(parsed) || parsed["format"] !== PORTABLE_RECOVERY_FORMAT || parsed["version"] !== PORTABLE_RECOVERY_VERSION ||
    typeof parsed["sourceRelease"] !== "string" || !Number.isInteger(parsed["totalChunks"]) ||
    typeof parsed["payloadCiphertextSha256"] !== "string" || !Number.isInteger(parsed["payloadCiphertextBytes"]) || !isUnknownArray(parsed["members"])) {
    fail("INTEGRITY_FAILED", "terminal manifest has an invalid shape");
  }
  const members: PortableRecoveryMemberManifest[] = [];
  const manifestMembers = parsed["members"];
  const sourceRelease = parsed["sourceRelease"];
  const totalChunks = parsed["totalChunks"];
  const payloadCiphertextSha256 = parsed["payloadCiphertextSha256"];
  const payloadCiphertextBytes = parsed["payloadCiphertextBytes"];
  if (!isUnknownArray(manifestMembers) || typeof sourceRelease !== "string" || !Number.isInteger(totalChunks) ||
    typeof payloadCiphertextSha256 !== "string" || !Number.isInteger(payloadCiphertextBytes)) fail("INTEGRITY_FAILED", "terminal manifest has an invalid shape");
  if (manifestMembers.length !== PORTABLE_RECOVERY_MEMBERS.length) fail("INTEGRITY_FAILED", "terminal manifest must contain every fixed member");
  for (let index = 0; index < PORTABLE_RECOVERY_MEMBERS.length; index += 1) {
    const member = manifestMembers[index];
    if (!isObject(member)) fail("INTEGRITY_FAILED", "terminal manifest member is invalid or noncanonical");
    const name = member["name"];
    const sha256 = member["sha256"];
    const plaintextBytes = member["plaintextBytes"];
    const chunks = member["chunks"];
    if (name !== PORTABLE_RECOVERY_MEMBERS[index] || typeof sha256 !== "string" ||
      !/^[a-f0-9]{64}$/.test(sha256) || typeof plaintextBytes !== "number" || !Number.isSafeInteger(plaintextBytes) || plaintextBytes < 0 ||
      typeof chunks !== "number" || !Number.isInteger(chunks) || chunks < 0) {
      fail("INTEGRITY_FAILED", "terminal manifest member is invalid or noncanonical");
    }
    members.push({
      name: PORTABLE_RECOVERY_MEMBERS[index]!,
      sha256,
      plaintextBytes,
      chunks,
    });
  }
  if (typeof totalChunks !== "number" || totalChunks < 0 || totalChunks > MAX_TOTAL_CHUNKS ||
    typeof payloadCiphertextBytes !== "number" || payloadCiphertextBytes < 0 ||
    typeof payloadCiphertextSha256 !== "string" || !/^[a-f0-9]{64}$/.test(payloadCiphertextSha256)) fail("INTEGRITY_FAILED", "terminal manifest bounds are invalid");
  const manifest: PortableRecoveryManifest = {
    format: PORTABLE_RECOVERY_FORMAT,
    version: PORTABLE_RECOVERY_VERSION,
    sourceRelease,
    totalChunks,
    payloadCiphertextSha256,
    payloadCiphertextBytes,
    members,
  };
  if (manifest.sourceRelease.length === 0 || TEXT_ENCODER.encode(manifest.sourceRelease).byteLength > MAX_SOURCE_RELEASE_BYTES) {
    fail("INTEGRITY_FAILED", "terminal manifest sourceRelease is invalid");
  }
  if (!equalBytes(bytes, manifestBytes(manifest))) fail("INTEGRITY_FAILED", "terminal manifest is not canonical");
  return manifest;
}

function validateExpectedReceipt(receipt: PortableRecoveryReceipt | undefined): void {
  if (receipt === undefined) return;
  if (!/^[a-f0-9]{64}$/.test(receipt.ciphertextSha256) || !Number.isSafeInteger(receipt.ciphertextBytes) || receipt.ciphertextBytes < 0) {
    fail("INVALID_INPUT", "expected receipt is invalid");
  }
}

/**
 * Authenticate and validate a container while streaming plaintext to a staging
 * sink. A bad terminal manifest or receipt rejects the whole operation, so the
 * caller must discard its staging area on rejection rather than promoting it.
 */
export async function readPortableRecovery(input: ReadPortableRecoveryInput): Promise<PortableRecoveryReadResult> {
  validateKey(input.key);
  validateExpectedReceipt(input.expectedReceipt);
  if (typeof input.onChunk !== "function") fail("INVALID_INPUT", "onChunk staging sink is required");
  // The reader is likewise asynchronous. Do not let post-construction caller
  // mutation change the authenticated key, receipt, source, or staging sink.
  const key = Uint8Array.from(input.key);
  const expectedReceipt = input.expectedReceipt === undefined ? undefined : { ...input.expectedReceipt };
  const source = input.source;
  const onChunk = input.onChunk;
  const digest = createHash("sha256");
  const count = { value: 0 };
  const reader = new ByteReader(source, digest, count);
  const magic = await reader.exact(MAGIC.byteLength);
  if (!equalBytes(magic, MAGIC)) fail("INVALID_FORMAT", "container magic does not match");
  const headerBytesLength = readU32(await reader.exact(4));
  if (headerBytesLength === 0 || headerBytesLength > MAX_HEADER_BYTES) fail("INVALID_FORMAT", "container header length is invalid");
  const nonceSeed = parseCanonicalHeader(await reader.exact(headerBytesLength));

  const memberStates = PORTABLE_RECOVERY_MEMBERS.map(() => ({ digest: createHash("sha256"), plaintextBytes: 0, chunks: 0 }));
  let totalChunks = 0;
  let lastMemberIndex = 0;
  let terminal: PortableRecoveryManifest | undefined;
  let terminalPreDigest = "";
  let terminalPreBytes = 0;

  for (;;) {
    terminalPreDigest = digest.copy().digest("hex");
    terminalPreBytes = count.value;
    const type = await reader.byte();
    const memberIndex = await reader.byte();
    const ordinal = readU32(await reader.exact(4));
    const plaintextBytes = readU32(await reader.exact(4));
    const ciphertextBytes = readU32(await reader.exact(4));
    if (ciphertextBytes !== plaintextBytes + TAG_BYTES) fail("INVALID_FORMAT", "frame ciphertext length is invalid");

    if (type === 1) {
      if (memberIndex >= PORTABLE_RECOVERY_MEMBERS.length || plaintextBytes === 0 || plaintextBytes > MAX_PORTABLE_RECOVERY_CHUNK_BYTES) {
        fail("INVALID_FORMAT", "data frame has invalid member or plaintext bounds");
      }
      if (memberIndex < lastMemberIndex || ordinal !== memberStates[memberIndex]!.chunks) {
        fail("NONCANONICAL_FRAME_ORDER", "data frames are not in canonical member/chunk order");
      }
      lastMemberIndex = memberIndex;
      const ciphertext = await reader.exact(ciphertextBytes);
      const member = PORTABLE_RECOVERY_MEMBERS[memberIndex]!;
      const plaintext = decrypt(
        key,
        derivePortableRecoveryNonce({ nonceSeed, memberIndex, ordinal, terminal: false }),
        aad({ member, ordinal, plaintextBytes, terminal: false }),
        ciphertext,
      );
      if (plaintext.byteLength !== plaintextBytes) fail("AUTH_FAILED", "authenticated plaintext length mismatch");
      const state = memberStates[memberIndex]!;
      state.digest.update(plaintext);
      state.plaintextBytes += plaintext.byteLength;
      state.chunks += 1;
      totalChunks += 1;
      if (totalChunks > MAX_TOTAL_CHUNKS) fail("INVALID_FORMAT", "too many recovery chunks");
      await onChunk({ member, ordinal, plaintext });
      continue;
    }

    if (type !== 2 || memberIndex !== 0xff || ordinal !== totalChunks || plaintextBytes === 0 || plaintextBytes > MAX_TERMINAL_MANIFEST_BYTES) {
      fail("NONCANONICAL_FRAME_ORDER", "terminal manifest frame is invalid or out of order");
    }
    const ciphertext = await reader.exact(ciphertextBytes);
    const plaintext = decrypt(
      key,
      derivePortableRecoveryNonce({ nonceSeed, memberIndex: 0xff, ordinal, terminal: true }),
      aad({ member: "terminal-manifest", ordinal, plaintextBytes, terminal: true }),
      ciphertext,
    );
    if (plaintext.byteLength !== plaintextBytes) fail("AUTH_FAILED", "authenticated terminal manifest length mismatch");
    terminal = parseManifest(plaintext);
    break;
  }

  await reader.assertEnd();
  if (terminal === undefined) fail("TRUNCATED", "container has no terminal manifest");
  if (terminal.totalChunks !== totalChunks || terminal.payloadCiphertextBytes !== terminalPreBytes || terminal.payloadCiphertextSha256 !== terminalPreDigest) {
    fail("INTEGRITY_FAILED", "terminal manifest does not commit to the received payload");
  }
  for (let index = 0; index < PORTABLE_RECOVERY_MEMBERS.length; index += 1) {
    const expected = terminal.members[index]!;
    const actual = memberStates[index]!;
    if (expected.name !== PORTABLE_RECOVERY_MEMBERS[index] || expected.chunks !== actual.chunks ||
      expected.plaintextBytes !== actual.plaintextBytes || expected.sha256 !== actual.digest.digest("hex")) {
      fail("INTEGRITY_FAILED", "terminal manifest member digest or byte count does not match payload");
    }
  }
  const receipt = { ciphertextSha256: digest.digest("hex"), ciphertextBytes: count.value };
  if (expectedReceipt !== undefined &&
    (expectedReceipt.ciphertextBytes !== receipt.ciphertextBytes || expectedReceipt.ciphertextSha256 !== receipt.ciphertextSha256)) {
    fail("RECEIPT_MISMATCH", "container does not match the expected ciphertext receipt");
  }
  return { manifest: terminal, receipt };
}
