import { describe, test, expect, beforeAll } from "bun:test";
import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import { mkdtempSync, writeFileSync, chmodSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawn } from "node:child_process";

const cliDist = join(import.meta.dirname, "..", "..", "dist", "index.js");

function spawnCliAsync(args: string[]): Promise<{ status: number; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [cliDist, ...args], {
      stdio: ["ignore", "pipe", "pipe"],
    });
    const out: Buffer[] = [];
    const err: Buffer[] = [];
    child.stdout?.on("data", (d: Buffer) => out.push(d));
    child.stderr?.on("data", (d: Buffer) => err.push(d));
    child.on("error", reject);
    child.on("close", (code) => {
      resolve({
        status: code ?? 0,
        stdout: Buffer.concat(out).toString("utf8"),
        stderr: Buffer.concat(err).toString("utf8"),
      });
    });
  });
}

function statusBody(setupState: string, genieCustomized: boolean) {
  return JSON.stringify({
    instanceId: "it-test",
    serverUrl: "http://127.0.0.1:9",
    deploymentMode: "local-self-host",
    setupState,
    claimRequired: false,
    viewer: {
      canManageServerSettings: true,
      genieCustomized,
      byokConfigured: true,
      pinEnrolled: false,
      handleAutoGenerated: false,
      passwordWasTemp: null,
    },
    recommendedSetupSurface: { kind: "cli", url: null },
  });
}

describe("Genie idempotent setup", () => {
  beforeAll(() => {
    if (!existsSync(cliDist)) {
      throw new Error(`missing ${cliDist}; run bun run build in apps/cli first`);
    }
  });

  test("second setup no-ops genie unless --force-genie", async () => {
    const server = createServer((req, res) => {
      const u = new URL(req.url ?? "/", `http://127.0.0.1`);
      if (u.pathname === "/api/setup/status") {
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(statusBody("ready", true));
        return;
      }
      res.writeHead(404);
      res.end();
    });

    const dir = mkdtempSync(join(tmpdir(), "nautilo-genie-"));
    const f = join(dir, "setup.toml");
    writeFileSync(
      f,
      [
        "schemaVersion = 1",
        "[admin]",
        'handle = "owner"',
        'displayName = "Owner"',
        'password = { value = "longenough1" }',
        'pin = { value = "654321" }',
        "[claim]",
        'inviteCode = { value = "x" }',
        "[genie]",
        'mode = "randomize"',
        "seed = 42",
      ].join("\n"),
    );
    try {
      chmodSync(f, 0o600);
    } catch {
      /* win32 */
    }

    await new Promise<void>((resolve, reject) => {
      server.listen(0, "127.0.0.1", () => resolve());
      server.on("error", reject);
    });
    const addr = server.address() as AddressInfo;
    const base = `http://127.0.0.1:${addr.port}`;
    try {
      const r = await spawnCliAsync(["setup", "--file", f, "--server", base]);
      expect(r.status).toBe(0);
      expect(r.stderr).toContain("already customized");
    } finally {
      await new Promise<void>((res) => server.close(() => res()));
    }
  });
});
