/**
 * D120 A5.3 (review fix) — regression coverage for the
 * "active local profile silently dials localhost:80" footgun.
 *
 * Before the follow-up, both `nautilo setup` and `nautilo login` constructed
 * `new NautiloApiClient(transport.baseUrl)` without forwarding
 * `transport.unixSocketPath`. With an active local profile and a
 * `~/.nautilo/server.sock` file, `resolveTransport()` returns
 * `baseUrl: "http://localhost"` plus `unixSocketPath`, but the api-client's
 * internal `fetch()` calls dropped the socket option and tried to dial
 * `localhost:80`. These tests assert that **every** outbound HTTP call
 * carries Bun's `unix:` request init when the resolved transport is socket-
 * bound.
 *
 * The tests stub `globalThis.fetch` to capture each call and assert that
 * `init.unix === <socket path>` for *every* HTTP method invoked by
 * `setup` (status, redeem, profile, reload-env, key-status, polling) and
 * `login` (whoami, device flow, password login). One escaped call would
 * mean the same regression resurfacing, just on a different endpoint.
 */
import { afterEach, beforeEach, describe, expect, mock, spyOn, test } from "bun:test";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { NautiloApiClient } from "@nautilo/api-client";

type CapturedFetch = {
  url: string;
  unix: string | undefined;
  method: string;
};

interface SpyRestorable {
  mockRestore(): void;
}

function setActiveLocalProfile(home: string): { socketPath: string } {
  // Profile + .active marker pointing at "local" target — mirrors
  // `nautilo profile create local && nautilo profile use local` with
  // a same-host server already running.
  const profilesDir = join(home, ".nautilo", "profiles");
  mkdirSync(profilesDir, { recursive: true });
  // `lifecycle = "external"` because the Unix-socket transport path is
  // the Bun-on-host dev-server flow (not the M092 containerized compose
  // stack, which never exposes a host socket).
  writeFileSync(
    join(profilesDir, "local.toml"),
    'name = "local"\ntransport = "local"\nlifecycle = "external"\nport = 3201\n',
  );
  writeFileSync(join(profilesDir, ".active"), "local");
  // The socket file must EXIST for resolveTransport() to pick the unix
  // path over TCP fallback. Touch a placeholder; we never actually
  // connect to it because fetch is stubbed.
  const nautiloDir = join(home, ".nautilo");
  const socketPath = join(nautiloDir, "server.sock");
  writeFileSync(socketPath, "");
  return { socketPath };
}

describe("profile-aware transport (review-fix regression)", () => {
  let home: string;
  let socketPath: string;
  let calls: CapturedFetch[];
  let fetchSpy: SpyRestorable;
  let prevHome: string | undefined;

  beforeEach(() => {
    mock.restore();
    process.exitCode = undefined;
    home = mkdtempSync(join(tmpdir(), "nautilo-socket-test-"));
    delete process.env["NAUTILO_TOKEN"];
    prevHome = process.env["HOME"];
    process.env["HOME"] = home;
    process.env["NAUTILO_HOME_OVERRIDE"] = home;
    const setup = setActiveLocalProfile(home);
    socketPath = setup.socketPath;

    calls = [];
    fetchSpy = spyOn(globalThis, "fetch").mockImplementation((async (
      input: string | URL | Request,
      init?: RequestInit & { unix?: string },
    ) => {
      const url =
        typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
      calls.push({
        url,
        unix: init?.unix,
        method: (init?.method ?? "GET").toUpperCase(),
      });
      // Sensible default response shapes per endpoint so the command
      // handler can finish without throwing on JSON parse.
      if (url.endsWith("/api/auth/whoami")) {
        return new Response(
          JSON.stringify({ sessionUserId: "u", mustChangePassword: false }),
          { status: 200, headers: { "Content-Type": "application/json" } },
        );
      }
      if (url.endsWith("/api/setup/status")) {
        return new Response(
          JSON.stringify({
            instanceId: "it-test",
            serverUrl: "http://localhost",
            deploymentMode: "local-self-host",
            setupState: "ready",
            claimRequired: false,
            viewer: {
              canManageServerSettings: true,
              genieCustomized: true,
              byokConfigured: true,
              pinEnrolled: false,
              handleAutoGenerated: false,
              passwordWasTemp: null,
            },
            recommendedSetupSurface: { kind: "cli", url: null },
          }),
          { status: 200, headers: { "Content-Type": "application/json" } },
        );
      }
      return new Response("{}", {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }) as unknown as typeof fetch) as SpyRestorable;
  });

  afterEach(() => {
    fetchSpy.mockRestore();
    if (prevHome !== undefined) {
      process.env["HOME"] = prevHome;
    } else {
      delete process.env["HOME"];
    }
    delete process.env["NAUTILO_HOME_OVERRIDE"];
    rmSync(home, { recursive: true, force: true });
    process.exitCode = undefined;
  });

  test("NautiloApiClient forwards unix option on every internal fetch", async () => {
    // Direct contract test on the api-client itself — this is the choke
    // point that the entire setup/login wiring relies on.
    const api = new NautiloApiClient("http://localhost", { unixSocketPath: socketPath });
    // Schema validation may reject our minimal mock body — that runs
    // AFTER fetch returns, so the call is captured either way. We only
    // care about the request init.
    await api.getSetupStatus().catch(() => {});
    expect(calls.length).toBe(1);
    expect(calls[0]?.unix).toBe(socketPath);
    expect(calls[0]?.url).toBe("http://localhost/api/setup/status");
  });

  test("setup --file routes setup-status over the unix socket (ready path)", async () => {
    // Setup template — uses the "ready" branch so we don't need to mock
    // the redeem/claim chain. The branch still calls getSetupStatus()
    // and applyGenieDefaults, both of which must ride the socket.
    const tplPath = join(home, "setup.toml");
    writeFileSync(
      tplPath,
      [
        "schemaVersion = 1",
        "[admin]",
        'handle = "owner"',
        'displayName = "Owner"',
        'password = { value = "longenough1" }',
        'pin = { value = "654321" }',
        "[claim]",
        'inviteCode = { value = "tok" }',
        "[genie]",
        'mode = "skip"',
      ].join("\n"),
    );
    try {
      chmodSync(tplPath, 0o600);
    } catch {
      /* win32 */
    }
    const { setupModule } = await import("../../src/commands/setup.ts");
    await (setupModule.handler as (a: unknown) => Promise<void>)({
      file: tplPath,
    });
    expect(process.exitCode).toBe(0);
    // status was fetched at least once (resolveTransport → getSetupStatus).
    const statusCalls = calls.filter((c) => c.url.endsWith("/api/setup/status"));
    expect(statusCalls.length).toBeGreaterThanOrEqual(1);
    // EVERY captured call must be socket-bound — no localhost:80 leak.
    for (const call of calls) {
      expect(call.unix).toBe(socketPath);
    }
  });
});
