import { describe, test, expect, afterEach } from "bun:test";
import { mkdtempSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { NautiloApiClient } from "@nautilo/api-client";
import { applyGenieDefaults } from "../../src/lib/apply-genie-defaults.ts";
import {
  parseSetupTemplateFromPath,
  resolveSetupTemplate,
} from "../../src/setup-template/loader.ts";

describe("setup bearer propagation (§14.3)", () => {
  const originalFetch = globalThis.fetch;

  afterEach(() => {
    globalThis.fetch = originalFetch;
  });

  test("PUT /api/profile uses Authorization: Bearer from redeem handoff", async () => {
    const authHeaders: string[] = [];
    const photoOrigins: string[] = [];
    globalThis.fetch = (async (url: string | URL, init?: RequestInit) => {
      const u = typeof url === "string" ? url : url.toString();
      const h = new Headers(init?.headers ?? undefined);
      const auth = h.get("Authorization");
      if (auth) authHeaders.push(`${u} :: ${auth}`);
      const photoOrigin = h.get("X-Agent-Photo-Origin");
      if (photoOrigin) photoOrigins.push(photoOrigin);
      if (u.endsWith("/api/setup/status")) {
        return Response.json({
          instanceId: "it-test",
          serverUrl: "http://127.0.0.1:9",
          deploymentMode: "local-self-host",
          setupState: "ready",
          claimRequired: false,
          viewer: {
            canManageServerSettings: true,
            genieCustomized: false,
            byokConfigured: true,
            pinEnrolled: false,
            handleAutoGenerated: false,
            passwordWasTemp: null,
          },
          recommendedSetupSurface: { kind: "cli", url: null },
        });
      }
      if (u.endsWith("/api/profile") && init?.method === "PUT") {
        return Response.json({ ok: true });
      }
      if (u.endsWith("/api/profile/agent-photo-library/current")) {
        const scope = {
            serverInstanceId: "00000000-0000-4000-8000-000000000001",
            viewerUserId: "00000000-0000-4000-8000-000000000002",
            agentId: "00000000-0000-4000-8000-000000000003",
            selectionRevision: "0",
            libraryRevision: "0",
          };
        return Response.json({
          current: { avatarRef: null, entryId: null, lastUndoableRevisionId: null, scope },
          scope,
        });
      }
      if (u.endsWith("/api/profile/agent-photo-library/select")) {
        return Response.json({
          operation: "select",
          changed: true,
          currentAvatarRef: { kind: "preset", id: "avatar-03" },
          currentEntryId: null,
          revisionId: "00000000-0000-4000-8000-000000000004",
          scope: {
            serverInstanceId: "00000000-0000-4000-8000-000000000001",
            viewerUserId: "00000000-0000-4000-8000-000000000002",
            agentId: "00000000-0000-4000-8000-000000000003",
            selectionRevision: "1",
            libraryRevision: "1",
          },
        });
      }
      return new Response("unexpected", { status: 500 });
    }) as typeof fetch;

    const dir = mkdtempSync(join(tmpdir(), "nautilo-bearer-"));
    const f = join(dir, "setup.toml");
    writeFileSync(
      f,
      [
        "schemaVersion = 1",
        "[admin]",
        'handle = "owner"',
        'displayName = "Owner"',
        'password = { value = "longenough1" }',
        'pin = { value = "654321" }',
        "[claim]",
        'inviteCode = { value = "tok" }',
        "[genie]",
        'mode = "explicit"',
        'name = "BearerTest"',
        'voice = "openai:nova"',
        'defaultModel = "openai:gpt-4o-mini"',
        'personality = "Warm test personality for bearer propagation unit test."',
        'avatar = { kind = "preset", presetId = "avatar-03" }',
      ].join("\n"),
    );
    try {
      chmodSync(f, 0o600);
    } catch {
      /* win32 */
    }

    const parsed = parseSetupTemplateFromPath(f);
    const template = resolveSetupTemplate(parsed, (n) => process.env[n]?.trim());

    const api = new NautiloApiClient("http://127.0.0.1:9");
    await applyGenieDefaults({
      transport: { baseUrl: "http://127.0.0.1:9", source: "flag" },
      api,
      template,
      argv: {},
      redeemBearer: "test-bearer",
    });

    const profileLine = authHeaders.find((s) => s.includes("/api/profile"));
    expect(profileLine).toBeDefined();
    expect(profileLine).toContain("Bearer test-bearer");
    expect(photoOrigins).toEqual(["cli_setup"]);
  });
});
