import { describe, test, expect, beforeAll } from "bun:test";
import { mkdtempSync, writeFileSync, chmodSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync, spawn } from "node:child_process";

const cliDist = join(import.meta.dirname, "..", "..", "dist", "index.js");

// Isolate HOME so the operator's active profile doesn't leak into the
// spawned CLI's `resolveTransport` (e.g. a remote `transport=remote`
// profile would short-circuit setup's loopback gate before any of
// these tests get to assert their actual subject).
const isolatedHome = mkdtempSync(join(tmpdir(), "nautilo-setup-cli-home-"));

function spawnCli(args: string[]) {
  return spawnSync(process.execPath, [cliDist, ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, HOME: isolatedHome },
  });
}

function spawnCliAsync(
  args: string[],
  envOverrides: Record<string, string> = {},
): Promise<{ status: number; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [cliDist, ...args], {
      stdio: ["ignore", "pipe", "pipe"],
      env: { ...process.env, HOME: isolatedHome, ...envOverrides },
    });
    const out: Buffer[] = [];
    const err: Buffer[] = [];
    child.stdout?.on("data", (d: Buffer) => out.push(d));
    child.stderr?.on("data", (d: Buffer) => err.push(d));
    child.on("error", reject);
    child.on("close", (code) => {
      resolve({
        status: code ?? 0,
        stdout: Buffer.concat(out).toString("utf8"),
        stderr: Buffer.concat(err).toString("utf8"),
      });
    });
  });
}

function statusBody(setupState: string, viewer?: { genieCustomized: boolean }) {
  return {
    instanceId: "it-test",
    serverUrl: "http://127.0.0.1:9",
    deploymentMode: "local-self-host" as const,
    setupState,
    claimRequired: setupState === "fresh-unclaimed",
    ...(viewer
      ? {
          viewer: {
            canManageServerSettings: true,
            genieCustomized: viewer.genieCustomized,
            byokConfigured: true,
            pinEnrolled: false,
            handleAutoGenerated: false,
            passwordWasTemp: null,
          },
        }
      : {}),
    recommendedSetupSurface: { kind: "cli" as const, url: null },
  };
}

describe("nautilo setup", () => {
  beforeAll(() => {
    if (!existsSync(cliDist)) {
      throw new Error(`missing ${cliDist}; run bun run build in apps/cli first`);
    }
  });

  test("--print-template emits quickstart TOML", () => {
    const r = spawnCli(["setup", "--print-template"]);
    expect(r.status).toBe(0);
    expect(r.stdout).toContain("schemaVersion");
    expect(r.stdout).toContain("[admin]");
  });

  test("non-loopback server is rejected", () => {
    const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
    const f = join(dir, "setup.toml");
    const toml = [
      "schemaVersion = 1",
      "[admin]",
      'handle = "owner"',
      'displayName = "Owner"',
      'password = { value = "longenough1" }',
      'pin = { value = "654321" }',
      "[claim]",
      'inviteCode = { value = "tok" }',
    ].join("\n");
    writeFileSync(f, toml);
    try {
      chmodSync(f, 0o600);
    } catch {
      /* win32 */
    }
    const r = spawnCli(["setup", "--file", f, "--server", "http://example.com"]);
    expect(r.status).toBe(2);
    expect(r.stderr).toContain("loopback");
  });

  test.skipIf(process.platform === "win32")("rejects setup file not chmod 600", () => {
    const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
    const f = join(dir, "setup.toml");
    writeFileSync(
      f,
      [
        "schemaVersion = 1",
        "[admin]",
        'handle = "owner"',
        'displayName = "Owner"',
        'password = { value = "longenough1" }',
        'pin = { value = "654321" }',
        "[claim]",
        'inviteCode = { value = "tok" }',
      ].join("\n"),
    );
    chmodSync(f, 0o644);
    const r = spawnCli(["setup", "--file", f]);
    expect(r.status).toBe(2);
    expect(r.stderr).toContain("chmod 600");
  });

  test("Zod validation failure exits 2", () => {
    const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
    const f = join(dir, "bad.toml");
    writeFileSync(f, "schemaVersion = 1\n[admin]\nhandle = \"\"\n");
    try {
      chmodSync(f, 0o600);
    } catch {
      /* win32 */
    }
    const r = spawnCli(["setup", "--file", f]);
    expect(r.status).toBe(2);
  });

  test("unsupported schemaVersion", () => {
    const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
    const f = join(dir, "bad.toml");
    writeFileSync(
      f,
      [
        "schemaVersion = 999",
        "[admin]",
        'handle = "owner"',
        'displayName = "Owner"',
        'password = { value = "longenough1" }',
        'pin = { value = "654321" }',
        "[claim]",
        'inviteCode = { value = "tok" }',
      ].join("\n"),
    );
    try {
      chmodSync(f, 0o600);
    } catch {
      /* win32 */
    }
    const r = spawnCli(["setup", "--file", f]);
    expect(r.status).toBe(2);
    expect(r.stderr).toContain("unsupported template schema version");
  });

  test("EnvVarMissingError shape", () => {
    const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
    const f = join(dir, "e.toml");
    writeFileSync(
      f,
      [
        "schemaVersion = 1",
        "[admin]",
        'handle = "owner"',
        'displayName = "Owner"',
        'password = { fromEnv = "NAUTILO_TEST_MISSING_XYZ" }',
        'pin = { value = "654321" }',
        "[claim]",
        'inviteCode = { value = "tok" }',
      ].join("\n"),
    );
    try {
      chmodSync(f, 0o600);
    } catch {
      /* win32 */
    }
    delete process.env["NAUTILO_TEST_MISSING_XYZ"];
    const r = spawnCli(["setup", "--file", f]);
    expect(r.status).toBe(2);
    expect(r.stderr).toContain("EnvVarMissingError");
    expect(r.stderr).toContain("NAUTILO_TEST_MISSING_XYZ");
  });

  test("idempotent re-run when ready (no genie)", async () => {
    let n = 0;
    const server = Bun.serve({
      port: 0,
      fetch() {
        n++;
        return Response.json(statusBody("ready", { genieCustomized: false }));
      },
    });
    try {
      const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
      const f = join(dir, "setup.toml");
      writeFileSync(
        f,
        [
          "schemaVersion = 1",
          "[admin]",
          'handle = "owner"',
          'displayName = "Owner"',
          'password = { value = "longenough1" }',
          'pin = { value = "654321" }',
          "[claim]",
          'inviteCode = { value = "tok" }',
        ].join("\n"),
      );
      try {
        chmodSync(f, 0o600);
      } catch {
        /* win32 */
      }
      const base = `http://127.0.0.1:${server.port}`;
      const r = await spawnCliAsync(["setup", "--file", f, "--server", base]);
      expect(r.status).toBe(0);
      expect(r.stderr).toContain("already ready");
      expect(n).toBeGreaterThanOrEqual(1);
      expect(existsSync(f)).toBe(true);
    } finally {
      server.stop();
    }
  });

  test("happy path: fresh-unclaimed redeem then ready", async () => {
    let statusN = 0;
    let redeemBody: unknown;
    const server = Bun.serve({
      port: 0,
      async fetch(req) {
        const u = new URL(req.url);
        if (u.pathname === "/api/setup/status") {
          statusN++;
          if (statusN === 1) {
            return Response.json(statusBody("fresh-unclaimed"));
          }
          return Response.json(statusBody("ready", { genieCustomized: false }));
        }
        if (u.pathname.includes("/api/invites/") && u.pathname.endsWith("/redeem")) {
          redeemBody = await req.json();
          return Response.json({
            ok: true,
            logtoSession: { accessToken: "test-access", expiresIn: 3600 },
          });
        }
        return new Response("not found", { status: 404 });
      },
    });
    try {
      const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
      const f = join(dir, "setup.toml");
      writeFileSync(
        f,
        [
          "schemaVersion = 1",
          "[admin]",
          'handle = "owner"',
          'displayName = "Owner"',
          'password = { value = "longenough1" }',
          'pin = { value = "654321" }',
          "[claim]",
          'inviteCode = { value = "claimtok" }',
        ].join("\n"),
      );
      try {
        chmodSync(f, 0o600);
      } catch {
        /* win32 */
      }
      const base = `http://127.0.0.1:${server.port}`;
      const r = await spawnCliAsync(["setup", "--file", f, "--server", base]);
      expect(r.status).toBe(0);
      expect(r.stderr).toContain("completed");
      expect(redeemBody).toEqual({
        handle: "owner",
        displayName: "Owner",
        password: "longenough1",
        pin: "654321",
        forcePasswordChange: false,
      });
      expect(existsSync(f)).toBe(true);
    } finally {
      server.stop();
    }
  });

  test("fresh-unclaimed redeem without session token still prints and stores recovery codes", async () => {
    let statusN = 0;
    const server = Bun.serve({
      port: 0,
      fetch(req) {
        const u = new URL(req.url);
        if (u.pathname === "/api/setup/status") {
          statusN++;
          return Response.json(
            statusN === 1
              ? statusBody("fresh-unclaimed")
              : statusBody("claimed-needs-auth"),
          );
        }
        if (u.pathname.includes("/api/invites/") && u.pathname.endsWith("/redeem")) {
          return Response.json({
            ok: true,
            recoveryCodes: ["rc-alpha", "rc-beta"],
          });
        }
        return new Response("not found", { status: 404 });
      },
    });
    try {
      const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
      const f = join(dir, "setup.toml");
      writeFileSync(
        f,
        [
          "schemaVersion = 1",
          "[admin]",
          'handle = "owner"',
          'displayName = "Owner"',
          'password = { value = "longenough1" }',
          'pin = { value = "654321" }',
          "[claim]",
          'inviteCode = { value = "claimtok" }',
        ].join("\n"),
      );
      try {
        chmodSync(f, 0o600);
      } catch {
        /* win32 */
      }
      const base = `http://127.0.0.1:${server.port}`;
      const r = await spawnCliAsync(
        ["setup", "--file", f, "--server", base],
        { NAUTILO_INSTANCE_ID: "setup-nosession" },
      );
      expect(r.status).toBe(2);
      expect(r.stdout).toContain("Recovery codes");
      expect(r.stdout).toContain("rc-alpha");
      expect(r.stderr).toContain("claim succeeded and recovery codes were written");
      const summaryPath = join(isolatedHome, ".nautilo-setup-nosession", "setup-summary.txt");
      expect(existsSync(summaryPath)).toBe(true);
    } finally {
      server.stop();
    }
  });

  test.skipIf(process.platform === "win32")("--delete-file shreds template", async () => {
    let statusN = 0;
    const server = Bun.serve({
      port: 0,
      fetch(req) {
        const u = new URL(req.url);
        if (u.pathname === "/api/setup/status") {
          statusN++;
          if (statusN === 1) {
            return Response.json(statusBody("fresh-unclaimed"));
          }
          return Response.json(statusBody("ready", { genieCustomized: false }));
        }
        if (u.pathname.includes("/api/invites/") && u.pathname.endsWith("/redeem")) {
          return Response.json({
            ok: true,
            logtoSession: { accessToken: "test-access", expiresIn: 3600 },
          });
        }
        return new Response("not found", { status: 404 });
      },
    });
    try {
      const dir = mkdtempSync(join(tmpdir(), "nautilo-setup-"));
      const f = join(dir, "setup.toml");
      writeFileSync(
        f,
        [
          "schemaVersion = 1",
          "[admin]",
          'handle = "owner"',
          'displayName = "Owner"',
          'password = { value = "longenough1" }',
          'pin = { value = "654321" }',
          "[claim]",
          'inviteCode = { value = "claimtok" }',
        ].join("\n"),
      );
      chmodSync(f, 0o600);
      const base = `http://127.0.0.1:${server.port}`;
      const r = await spawnCliAsync(["setup", "--file", f, "--server", base, "--delete-file"]);
      expect(r.status).toBe(0);
      expect(existsSync(f)).toBe(false);
    } finally {
      server.stop();
    }
  });
});
