import { describe, test, expect, beforeAll } from "bun:test";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { spawnSync, spawn } from "node:child_process";
import { setupStatusResponseSchema } from "@nautilo/api-client";

const cliDist = join(import.meta.dirname, "..", "..", "dist", "index.js");

function spawnCli(args: string[]) {
  return spawnSync(process.execPath, [cliDist, ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
}

function spawnCliAsync(args: string[]): Promise<{ status: number; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [cliDist, ...args], {
      stdio: ["ignore", "pipe", "pipe"],
    });
    const out: Buffer[] = [];
    const err: Buffer[] = [];
    child.stdout?.on("data", (d: Buffer) => out.push(d));
    child.stderr?.on("data", (d: Buffer) => err.push(d));
    child.on("error", reject);
    child.on("close", (code) => {
      resolve({
        status: code ?? 0,
        stdout: Buffer.concat(out).toString("utf8"),
        stderr: Buffer.concat(err).toString("utf8"),
      });
    });
  });
}

describe("nautilo status", () => {
  beforeAll(() => {
    if (!existsSync(cliDist)) {
      throw new Error(`missing ${cliDist}; run bun run build in apps/cli first`);
    }
  });

  test("exit 2 when server unreachable", () => {
    const r = spawnCli(["status", "--server", "http://127.0.0.1:59999", "--format", "json"]);
    expect(r.status).toBe(2);
    const j = JSON.parse(r.stdout) as { ok: boolean; error?: string };
    expect(j.ok).toBe(false);
    expect(typeof j.error).toBe("string");
  });

  test("exit 0 on ready, 2 on fresh-unclaimed", async () => {
    const server = Bun.serve({
      port: 0,
      fetch() {
        return Response.json({
          instanceId: "x",
          serverUrl: "http://127.0.0.1:1",
          deploymentMode: "local-self-host",
          setupState: "ready",
          claimRequired: false,
          viewer: {
            canManageServerSettings: true,
            genieCustomized: true,
            byokConfigured: true,
            pinEnrolled: false,
            handleAutoGenerated: false,
            passwordWasTemp: null,
          },
          providers: { hasLlm: true, managedByCloud: false },
          recommendedSetupSurface: { kind: "cli", url: null },
        });
      },
    });
    try {
      const base = `http://127.0.0.1:${server.port}`;
      const r0 = await spawnCliAsync(["status", "--server", base, "--format", "json"]);
      expect(r0.status).toBe(0);
      const body = setupStatusResponseSchema.parse(JSON.parse(r0.stdout));
      expect(body.setupState).toBe("ready");
    } finally {
      server.stop();
    }

    const bad = Bun.serve({
      port: 0,
      fetch() {
        return Response.json({
          instanceId: "x",
          serverUrl: "http://127.0.0.1:1",
          deploymentMode: "local-self-host",
          setupState: "fresh-unclaimed",
          claimRequired: true,
          recommendedSetupSurface: { kind: "cli", url: null },
        });
      },
    });
    try {
      const base = `http://127.0.0.1:${bad.port}`;
      const r2 = await spawnCliAsync(["status", "--server", base, "--format", "human"]);
      expect(r2.status).toBe(2);
      expect(r2.stdout).toContain("fresh-unclaimed");
    } finally {
      bad.stop();
    }
  }, 15000);
});
