import { DynamicStructuredTool } from "@langchain/core/tools";
import { z } from "zod";

const googleWorkspaceCommand = z.enum([
  "docs.cat",
  "docs.info",
  "docs.create",
  "docs.copy",
  "docs.raw",
  "docs.structure",
  "docs.listTabs",
  "docs.addTab",
  "docs.renameTab",
  "docs.deleteTab",
  "docs.headings",
  "docs.paragraphs",
  "docs.tablesList",
  "docs.imagesList",
  "docs.findRange",
  "docs.export",
  "docs.format",
  "docs.update",
  "docs.insert",
  "docs.insertTable",
  "docs.insertImage",
  "docs.replaceImage",
  "docs.insertPerson",
  "docs.insertFileChip",
  "docs.insertDateChip",
  "docs.insertPageBreak",
  "docs.insertFootnote",
  "docs.insertSectionBreak",
  "docs.insertHorizontalRule",
  "docs.sectionColumns",
  "docs.delete",
  "docs.clear",
  "docs.sed",
  "docs.pageLayout",
  "docs.writeAppend",
  "docs.findReplace",
  "docs.namedRangesList",
  "docs.namedRangesCreate",
  "docs.namedRangesDelete",
  "docs.namedRangesReplace",
  "docs.commentsList",
  "docs.commentsPoll",
  "docs.commentsGet",
  "docs.commentsAdd",
  "docs.commentsReply",
  "docs.commentsResolve",
  "docs.commentsReopen",
  "docs.commentsDelete",
  "docs.commentsLocate",
  "docs.headersList",
  "docs.headersCreate",
  "docs.headersDelete",
  "docs.footersList",
  "docs.footersCreate",
  "docs.footersDelete",
  "docs.cellUpdate",
  "docs.cellStyle",
  "docs.tableRowInsert",
  "docs.tableRowDelete",
  "docs.tableRowStyle",
  "docs.tableRowPinHeader",
  "docs.tableColumnInsert",
  "docs.tableColumnDelete",
  "docs.tableMerge",
  "docs.tableUnmerge",
  "docs.tableColumnWidth",
  "drive.ls",
  "drive.search",
  "drive.fileInfo",
  "gmail.search",
  "gmail.get",
  "gmail.threadGet",
  "calendar.eventsToday",
  "calendar.createDryRun",
  "sheets.get",
  "sheets.metadata",
  "sheets.raw",
  "sheets.create",
  "sheets.export",
  "sheets.update",
  "sheets.append",
  "sheets.clear",
  "sheets.addTab",
  "sheets.renameTab",
  "sheets.chartList",
  "sheets.chartGet",
  "sheets.chartCreate",
  "sheets.chartUpdate",
  "sheets.chartDelete",
  "sheets.tableList",
  "sheets.tableGet",
  "sheets.tableCreate",
  "sheets.tableAppend",
  "sheets.tableClear",
  "sheets.tableDelete",
  "sheets.conditionalFormatList",
  "sheets.conditionalFormatAdd",
  "sheets.conditionalFormatClear",
  "sheets.validationGet",
  "sheets.validationSet",
  "sheets.validationClear",
  "sheets.namedRangesList",
  "sheets.namedRangesGet",
  "sheets.namedRangesAdd",
  "sheets.namedRangesUpdate",
  "sheets.namedRangesDelete",
  "sheets.linksGet",
  "sheets.linksSet",
  "slides.info",
  "slides.listSlides",
]);

export function createGoogleWorkspaceTool() {
  return new DynamicStructuredTool({
    name: "google_workspace",
    description:
      "Use the local `gog` Google Workspace CLI through Nautilo's desktop relay. " +
      "Use this for API-backed Google Docs/Drive/Gmail/Calendar/Sheets/Slides work when you need " +
      "structural truth or background operations instead of visible browser UI control. " +
      "Read commands are automatically run with gog's --readonly, --json, --wrap-untrusted, " +
      "and --no-input safety defaults. Gmail reads use --sanitize-content. For visible co-editing " +
      "inside an open web app, use browser_* tools instead. For Google Docs, prefer docs.cat/raw/structure/info " +
      "to read first; Docs wrappers cover file ops, tabs, comments, images, smart chips, page layout, named ranges, " +
      "and native tables. Use docs.findRange to resolve UTF-16 ranges before exact edits. Drive: drive.search " +
      "and drive.fileInfo for discovery. Gmail: search/get/threadGet only — no send. Calendar: reads plus " +
      "calendar.createDryRun (dryRun:true required; live create not enabled). Sheets: values, tabs, charts, tables, " +
      "conditional formatting, validation, named ranges, hyperlinks, create/export/raw. Slides: slides.info and slides.listSlides. Always identify the account/object " +
      "before writes; set dryRun:true first when available.",
    schema: z.object({
      command: googleWorkspaceCommand.describe("Allowed gog command wrapper to run"),
      account: z
        .string()
        .optional()
        .describe("Google account email or alias. Omit to let gog use account=auto."),
      docId: z.string().optional().describe("Google Docs document ID for docs.* commands"),
      text: z.string().optional().describe("Text for docs.writeAppend"),
      title: z.string().optional().describe("Title for sheets.create"),
      content: z.string().optional().describe("Content for docs.insert/comments"),
      find: z.string().optional().describe("Text to find for docs.findReplace"),
      replace: z.string().optional().describe("Replacement text for docs.findReplace"),
      match: z.string().optional().describe("Text to match for docs.format"),
      first: z.boolean().optional().describe("For docs.findReplace, replace only first match"),
      all: z.boolean().optional().describe("For docs.findRange/format, apply to all matches"),
      matchCase: z.boolean().optional().describe("Use case-sensitive matching"),
      dryRun: z.boolean().optional().describe("Preview supported writes without mutating"),
      format: z.enum(["pdf", "docx", "txt", "md", "html", "xlsx", "csv"]).optional().describe("Export format for docs.export or sheets.export"),
      out: z.string().optional().describe("Output path for docs.export or sheets.export"),
      overwrite: z.boolean().optional().describe("Overwrite an existing export output file"),
      tab: z.string().optional().describe("Google Docs tab title or ID"),
      parentTab: z.string().optional().describe("Parent tab title or ID for docs.addTab"),
      iconEmoji: z.string().optional().describe("Emoji icon for docs.addTab"),
      index: z.number().int().positive().optional().describe("Docs API UTF-16 insertion index for docs.update"),
      start: z.number().int().positive().optional().describe("Docs API UTF-16 start index"),
      end: z.number().int().positive().optional().describe("Docs API UTF-16 end index"),
      replaceRange: z.string().optional().describe("Docs API UTF-16 range START:END for docs.update"),
      at: z.string().optional().describe("Literal text anchor for docs.update"),
      before: z.string().optional().describe("Literal text before which to insert a docs image"),
      after: z.string().optional().describe("Literal text after which to insert a docs image"),
      atEnd: z.boolean().optional().describe("Insert at end of doc/tab"),
      occurrence: z.number().int().positive().optional().describe("Nth match/anchor occurrence, 1-based"),
      markdown: z.boolean().optional().describe("Treat docs.update text as markdown"),
      pageless: z.boolean().optional().describe("Create doc in pageless mode"),
      segment: z.string().optional().describe("Header/footer/footnote segment ID"),
      batch: z.string().optional().describe("Persisted Docs batch name"),
      rows: z.number().int().positive().optional().describe("Rows for docs.insertTable"),
      cols: z.number().int().positive().optional().describe("Columns for docs.insertTable"),
      objectId: z.string().optional().describe("Image object ID for docs.replaceImage"),
      matchAlt: z.string().optional().describe("Alt text matcher for docs.replaceImage"),
      email: z.string().optional().describe("Email address for docs.insertPerson"),
      date: z.string().optional().describe("Date for docs.insertDateChip"),
      dateFormat: z.string().optional().describe("Date chip display format"),
      sectionType: z.string().optional().describe("Section break type"),
      count: z.number().int().positive().optional().describe("Count for docs.sectionColumns"),
      expression: z.string().optional().describe("Sed expression for docs.sed"),
      expressions: z.array(z.string()).optional().describe("Additional sed expressions for docs.sed"),
      layout: z.string().optional().describe("Docs page layout: pageless or pages"),
      pageSize: z.string().optional().describe("Docs page size"),
      pageWidth: z.string().optional().describe("Docs page width"),
      pageHeight: z.string().optional().describe("Docs page height"),
      marginLeft: z.string().optional().describe("Docs page left margin"),
      marginRight: z.string().optional().describe("Docs page right margin"),
      marginTop: z.string().optional().describe("Docs page top margin"),
      marginBottom: z.string().optional().describe("Docs page bottom margin"),
      nameOrId: z.string().optional().describe("Named range name or ID"),
      commentId: z.string().optional().describe("Google Docs comment ID"),
      stateFile: z.string().optional().describe("State file for docs.commentsPoll"),
      interval: z.string().optional().describe("Polling interval for docs.commentsPoll"),
      includeResolved: z.boolean().optional().describe("Include resolved comments in docs.commentsPoll"),
      maxIterations: z.number().int().positive().optional().describe("Maximum comment poll iterations"),
      quoted: z.string().optional().describe("Quoted text for docs.commentsAdd"),
      anchor: z.string().optional().describe("Advanced anchor JSON or chart/image anchor"),
      action: z.string().optional().describe("Comment reply action: resolve or reopen"),
      message: z.string().optional().describe("Optional comment resolution message"),
      segmentId: z.string().optional().describe("Header/footer segment ID"),
      table: z.string().optional().describe("Docs table selector"),
      tableIndex: z.number().int().positive().optional().describe("1-based Docs table index"),
      row: z.number().int().positive().optional().describe("1-based Docs table row"),
      col: z.number().int().positive().optional().describe("1-based Docs table column"),
      rowSpan: z.number().int().positive().optional().describe("Docs table cell row span"),
      colSpan: z.number().int().positive().optional().describe("Docs table cell column span"),
      minHeight: z.string().optional().describe("Docs table row minimum height"),
      preventOverflow: z.boolean().optional().describe("Docs table row overflow behavior"),
      contentFile: z.string().optional().describe("File containing docs cell/insert content"),
      append: z.boolean().optional().describe("Append into a docs table cell"),
      backgroundColor: z.string().optional().describe("Docs table cell background color"),
      borderAll: z.string().optional().describe("Docs table cell border shorthand"),
      paddingAll: z.string().optional().describe("Docs table cell padding shorthand"),
      contentAlign: z.string().optional().describe("Docs table cell vertical alignment"),
      cell: z.string().optional().describe("Docs table cell selector or Sheets link cell"),
      evenlyDistributed: z.boolean().optional().describe("Reset Docs table column widths evenly"),
      bold: z.boolean().optional().describe("Set/clear bold for docs.format"),
      italic: z.boolean().optional().describe("Set/clear italic for docs.format"),
      underline: z.boolean().optional().describe("Set/clear underline for docs.format"),
      strikethrough: z.boolean().optional().describe("Set/clear strikethrough for docs.format"),
      headingLevel: z.string().optional().describe("Heading level for docs.format, e.g. HEADING_1"),
      fontFamily: z.string().optional().describe("Font family for docs.format"),
      fontSize: z.number().positive().optional().describe("Font size in points for docs.format"),
      textColor: z.string().optional().describe("Text color, e.g. #336699"),
      bgColor: z.string().optional().describe("Background color, e.g. #ffff00"),
      alignment: z.string().optional().describe("Paragraph alignment for docs.format"),
      query: z.string().optional().describe("Search query for drive.search or gmail.search"),
      max: z.number().int().positive().optional().describe("Maximum results for list/search commands"),
      fileId: z.string().optional().describe("Drive file ID for drive.fileInfo"),
      fields: z.string().optional().describe("Drive API field mask for drive.fileInfo"),
      rawQuery: z.boolean().optional().describe("For drive.search, treat query as Drive query language"),
      parent: z.string().optional().describe("For drive.search, scope to children of this folder ID"),
      messageId: z.string().optional().describe("Gmail message ID for gmail.get"),
      messageFormat: z
        .enum(["full", "metadata", "raw"])
        .optional()
        .describe("Gmail payload format for gmail.get (default full)"),
      threadId: z.string().optional().describe("Gmail thread ID for gmail.threadGet"),
      calendarId: z.string().optional().describe("Calendar ID for calendar.createDryRun"),
      summary: z.string().optional().describe("Event title for calendar.createDryRun"),
      from: z.string().optional().describe("Event start time RFC3339 for calendar.createDryRun"),
      to: z.string().optional().describe("Event end time RFC3339 for calendar.createDryRun"),
      description: z.string().optional().describe("Event description for calendar.createDryRun"),
      location: z.string().optional().describe("Event location for calendar.createDryRun"),
      timezone: z.string().optional().describe("IANA timezone for calendar.createDryRun"),
      spreadsheetId: z.string().optional().describe("Spreadsheet ID for sheets.* commands"),
      range: z.string().optional().describe("A1 range for sheets.get, e.g. Sheet1!A1:D20"),
      values: z.array(z.string()).optional().describe("Values for sheets.update/append as gog row strings"),
      valuesJson: z.string().optional().describe("JSON 2D values array for sheets.update/append"),
      input: z.enum(["RAW", "USER_ENTERED"]).optional().describe("Sheets value input option"),
      insert: z.enum(["OVERWRITE", "INSERT_ROWS"]).optional().describe("Sheets append insert mode"),
      failOnFormulaError: z.boolean().optional().describe("Fail sheets.update if readback finds formula errors"),
      sheets: z.array(z.string()).optional().describe("Initial sheet/tab names for sheets.create"),
      tabName: z.string().optional().describe("Tab name for sheets.addTab"),
      tabIndex: z.number().int().nonnegative().optional().describe("Zero-based tab index for sheets.addTab"),
      oldName: z.string().optional().describe("Current tab name for sheets.renameTab"),
      newName: z.string().optional().describe("New tab name for sheets.renameTab"),
      chartId: z.string().optional().describe("Chart ID for sheets.chart* commands"),
      specJson: z.string().optional().describe("Chart spec JSON or @file for sheets.chartCreate/update"),
      sheet: z.string().optional().describe("Sheet/tab name for charts or conditional formatting"),
      width: z.number().int().positive().optional().describe("Chart width in pixels"),
      height: z.number().int().positive().optional().describe("Chart height in pixels"),
      tableId: z.string().optional().describe("Table ID or table name for sheets.table* commands"),
      name: z.string().optional().describe("Name for tables or named ranges"),
      columnsJson: z.string().optional().describe("Table column definitions JSON or @file"),
      discardData: z.boolean().optional().describe("Delete table cells too for sheets.tableDelete"),
      ruleType: z.string().optional().describe("Conditional format rule type"),
      expr: z.string().optional().describe("Conditional format expression or custom formula"),
      formatJson: z.string().optional().describe("CellFormat JSON or @file for conditional formatting"),
      formatFields: z.string().optional().describe("Conditional format field mask"),
      ruleIndex: z.union([z.string(), z.number().int().nonnegative()]).optional().describe("Conditional format rule index"),
      validationType: z.string().optional().describe("Sheets data validation condition type"),
      validationValues: z.array(z.string()).optional().describe("Values for data validation conditions"),
      strict: z.boolean().optional().describe("Whether validation rejects invalid input"),
      showCustomUi: z.boolean().optional().describe("Whether validation shows dropdown/checkbox UI"),
      inputMessage: z.string().optional().describe("Data validation input message"),
      filteredRowsIncluded: z.boolean().optional().describe("Apply validation to filtered rows"),
      url: z.string().optional().describe("URL for sheets.linksSet"),
      linkText: z.string().optional().describe("Display text for sheets.linksSet"),
      runsJson: z.string().optional().describe("Rich text runs JSON for sheets.linksSet"),
      cellsJson: z.string().optional().describe("Batch cell/link JSON for sheets.linksSet"),
      render: z
        .enum(["FORMATTED_VALUE", "UNFORMATTED_VALUE", "FORMULA"])
        .optional()
        .describe("Value render option for sheets.get"),
      dimension: z.enum(["ROWS", "COLUMNS"]).optional().describe("Major dimension for sheets.get"),
      presentationId: z.string().optional().describe("Presentation ID for slides.* commands"),
    }),
    func: () => {
      return Promise.reject(
        new Error(
          "google_workspace is a relay tool — execution goes through the relay protocol, not direct invocation. If you see this error, the tool routing in toolsNode is broken.",
        ),
      );
    },
  });
}
